/** @file save_tables_decl.h
 *     Declarations of every struct table.
 */
#ifndef KFX_SAVE_TABLES_DECL_H
#define KFX_SAVE_TABLES_DECL_H

#include "kfx/save/core/save_schema.h"

#ifdef __cplusplus
extern "C" {
#endif

SAVE_DECLARE(ActionPoint);
SAVE_DECLARE(Ariadne);
SAVE_DECLARE(Bookmark);
SAVE_DECLARE(BoxInfo);
SAVE_DECLARE(DungeonCamera);
SAVE_DECLARE(CastedSpellData);
SAVE_DECLARE(CatalogueEntry);
SAVE_DECLARE(CheatSelection);
SAVE_DECLARE(Column);
SAVE_DECLARE(ColumnConfig);
SAVE_DECLARE(CommandWord);
SAVE_DECLARE(ComponentVector);
SAVE_DECLARE(Computer2);
SAVE_DECLARE(ComputerCheck);
SAVE_DECLARE(ComputerDig);
SAVE_DECLARE(ComputerEvent);
SAVE_DECLARE(ComputerProcess);
SAVE_DECLARE(ComputerRulesConfig);
SAVE_DECLARE(ComputerTask);
SAVE_DECLARE(ComputerTask_attack_magic);
SAVE_DECLARE(ComputerTask_create_room);
SAVE_DECLARE(ComputerTask_dig_somewhere);
SAVE_DECLARE(ComputerTask_dig_to_gold);
SAVE_DECLARE(ComputerTask_dig_to_room);
SAVE_DECLARE(ComputerTask_magic_cta);
SAVE_DECLARE(ComputerTask_move_gold);
SAVE_DECLARE(ComputerTask_move_to_defend);
SAVE_DECLARE(ComputerTask_move_to_pos);
SAVE_DECLARE(ComputerTask_move_to_room);
SAVE_DECLARE(ComputerTask_pickup_for_attack);
SAVE_DECLARE(ComputerTask_sacrifice_imp);
SAVE_DECLARE(ComputerTask_sell_traps_doors);
SAVE_DECLARE(ComputerTask_slap_imps);
SAVE_DECLARE(Condition);
SAVE_DECLARE(ConfigInfo);
SAVE_DECLARE(Configs);
SAVE_DECLARE(ContinueData);
SAVE_DECLARE(Coord2d);
SAVE_DECLARE(Coord3d);
SAVE_DECLARE(CoordDelta3d);
SAVE_DECLARE(CreatureAngerJobConfig);
SAVE_DECLARE(CreatureBattle);
SAVE_DECLARE(CreatureConfig);
SAVE_DECLARE(CreatureControl);
SAVE_DECLARE(CreatureExperience);
SAVE_DECLARE(CreatureInstanceConfig);
SAVE_DECLARE(CreatureJobConfig);
SAVE_DECLARE(CreatureModelConfig);
SAVE_DECLARE(CreaturePool);
SAVE_DECLARE(CreatureRulesConfig);
SAVE_DECLARE(CreatureSound);
SAVE_DECLARE(CreatureSounds);
SAVE_DECLARE(CreatureStateConfig);
SAVE_DECLARE(CreatureStorage);
SAVE_DECLARE(CubeConfigStats);
SAVE_DECLARE(CubesConfig);
SAVE_DECLARE(DesyncChecksums);
SAVE_DECLARE(DiggerStack);
SAVE_DECLARE(DoorConfigStats);
SAVE_DECLARE(Dungeon);
SAVE_DECLARE(EffectConfigStats);
SAVE_DECLARE(EffectElementConfigStats);
SAVE_DECLARE(EffectGeneratorConfigStats);
SAVE_DECLARE(Effects);
SAVE_DECLARE(EffectsConfig);
SAVE_DECLARE(Event);
SAVE_DECLARE(FileChunkHeader);
SAVE_DECLARE(FlameProperties);
SAVE_DECLARE(Game);
SAVE_DECLARE(GameRulesConfig);
SAVE_DECLARE(GoldLookup);
SAVE_DECLARE(GuiMessage);
SAVE_DECLARE(HandRule);
SAVE_DECLARE(HealthRulesConfig);
SAVE_DECLARE(HighScore);
SAVE_DECLARE(InitLight);
SAVE_DECLARE(InstanceInfo);
SAVE_DECLARE(IntralevelData);
SAVE_DECLARE(LevelEnsignOverride);
SAVE_DECLARE(LevelScript);
SAVE_DECLARE(LevelStats);
SAVE_DECLARE(Light);
SAVE_DECLARE(LightSystemState);
SAVE_DECLARE(LightingTable);
SAVE_DECLARE(LightsShadows);
SAVE_DECLARE(LogDetailedSnapshot);
SAVE_DECLARE(LogPlayerDesyncInfo);
SAVE_DECLARE(LogRoomDesyncInfo);
SAVE_DECLARE(LogThingDesyncInfo);
SAVE_DECLARE(LuaFuncsConf);
SAVE_DECLARE(MagicConfig);
SAVE_DECLARE(MagicRulesConfig);
SAVE_DECLARE(ManufactureData);
SAVE_DECLARE(Map);
SAVE_DECLARE(MapTask);
SAVE_DECLARE(MemberPos);
SAVE_DECLARE(Modifiers);
SAVE_DECLARE(Navigation);
SAVE_DECLARE(ObjectConfigStats);
SAVE_DECLARE(ObjectsConfig);
SAVE_DECLARE(OpponentRelation);
SAVE_DECLARE(Packet);
SAVE_DECLARE(PacketSaveHead);
SAVE_DECLARE(Party);
SAVE_DECLARE(PartyMember);
SAVE_DECLARE(PartyTrigger);
SAVE_DECLARE(PerExpLevelValues);
SAVE_DECLARE(PickedUpOffset);
SAVE_DECLARE(PlayerInfo);
SAVE_DECLARE(PlayerStateConfig);
SAVE_DECLARE(PlayerStateConfigStats);
SAVE_DECLARE(PowerConfigStats);
SAVE_DECLARE(PowerHandConfig);
SAVE_DECLARE(PowerHandConfigStats);
SAVE_DECLARE(ResearchVal);
SAVE_DECLARE(Room);
SAVE_DECLARE(RoomConfigStats);
SAVE_DECLARE(RoomRulesConfig);
SAVE_DECLARE(RoomSpace);
SAVE_DECLARE(RulesConfig);
SAVE_DECLARE(SacrificeRecipe);
SAVE_DECLARE(SacrificesRulesConfig);
SAVE_DECLARE(ScriptFxLine);
SAVE_DECLARE(ScriptValue);
SAVE_DECLARE(ScriptVariable);
SAVE_DECLARE(ShadowCache);
SAVE_DECLARE(ShotConfigStats);
SAVE_DECLARE(ShotDetonateConfig);
SAVE_DECLARE(ShotHitConfig);
SAVE_DECLARE(ShotVisualConfig);
SAVE_DECLARE(SlabConfigStats);
SAVE_DECLARE(SlabMap);
SAVE_DECLARE(SlabObj);
SAVE_DECLARE(SlabSet);
SAVE_DECLARE(SlabsConfig);
SAVE_DECLARE(SoundSettings);
SAVE_DECLARE(SpecialConfigStats);
SAVE_DECLARE(SpeechRef);
SAVE_DECLARE(SpellConfig);
SAVE_DECLARE(SpellConfigStats);
SAVE_DECLARE(StructureList);
SAVE_DECLARE(SubtileXY);
SAVE_DECLARE(TextScrollWindow);
SAVE_DECLARE(Thing);
SAVE_DECLARE(Thing_armor);
SAVE_DECLARE(Thing_cave_in);
SAVE_DECLARE(Thing_corpse);
SAVE_DECLARE(Thing_creature);
SAVE_DECLARE(Thing_door);
SAVE_DECLARE(Thing_effect_generator);
SAVE_DECLARE(Thing_food);
SAVE_DECLARE(Thing_heart);
SAVE_DECLARE(Thing_lair);
SAVE_DECLARE(Thing_price_effect);
SAVE_DECLARE(Thing_roomflag);
SAVE_DECLARE(Thing_shot);
SAVE_DECLARE(Thing_shot_effect);
SAVE_DECLARE(Thing_shot_lizard);
SAVE_DECLARE(Thing_trap);
SAVE_DECLARE(Thing_valuable);
SAVE_DECLARE(TrapConfigStats);
SAVE_DECLARE(TrapDoorConfig);
SAVE_DECLARE(TrapInfo);
SAVE_DECLARE(TunnellerTrigger);
SAVE_DECLARE(TurnTimer);
SAVE_DECLARE(UserState);
SAVE_DECLARE(Wander);
SAVE_DECLARE(WorkersRulesConfig);
SAVE_DECLARE_UNION(ComputerTask_u_sell_traps_doors);
SAVE_DECLARE_UNION(Thing_u_valuable);

#ifdef __cplusplus
}
#endif

#endif
