/** @file schema_things.c
 *     Field tables for saved structs.
 */
#include "pre_inc.h"
#include "kfx/save/SaveTypes.h"
#include "kfx/save/SaveUnionArms.h"
#include "game_legacy.h"
#include "game_merge.h"
#include "packets.h"
#include "config_campaigns.h"
#include "front_network.h"
#include "post_inc.h"
#include "kfx/save/core/save_schema.h"
#include "kfx/save/core/schema/save_tables_decl.h"

SAVE_STRUCT(Ariadne, struct Ariadne,
    SAVE_SUB(struct Ariadne, startpos, Coord3d),
    SAVE_SUB(struct Ariadne, endpos, Coord3d),
    SAVE_SUB(struct Ariadne, current_waypoint_pos, Coord3d),
    SAVE_SUB(struct Ariadne, next_position, Coord3d),
    SAVE_SUB(struct Ariadne, previous_position, Coord3d),
    SAVE_FIELD(struct Ariadne, route_flags, SV_U8),
    SAVE_FIELD(struct Ariadne, hug_side, SV_U8),
    SAVE_FIELD(struct Ariadne, update_state, SV_U8),
    SAVE_FIELD(struct Ariadne, wallhug_active, SV_U8),
    SAVE_FIELD(struct Ariadne, may_need_reroute, SV_U8),
    SAVE_FIELD(struct Ariadne, wallhug_stored_angle, SV_I16),
    SAVE_FIELD(struct Ariadne, move_speed, SV_U16),
    SAVE_FIELD(struct Ariadne, current_waypoint, SV_U8),
    SAVE_SUB_ARRAY(struct Ariadne, waypoints, Coord2d),
    SAVE_FIELD(struct Ariadne, stored_waypoints, SV_U8),
    SAVE_FIELD(struct Ariadne, total_waypoints, SV_U32),
    SAVE_SUB(struct Ariadne, manoeuvre_fixed_position, Coord3d),
    SAVE_SUB(struct Ariadne, manoeuvre_requested_position, Coord3d),
    SAVE_FIELD(struct Ariadne, manoeuvre_state, SV_U8),
    SAVE_FIELD(struct Ariadne, wallhug_angle, SV_I16),
    SAVE_FIELD(struct Ariadne, straight_dist_to_next_waypoint, SV_I32),
);

SAVE_STRUCT(CastedSpellData, struct CastedSpellData,
    SAVE_FIELD_EX(struct CastedSpellData, spkind, SV_U16, .flags = 0, .name_domain = SND_Spell),
    SAVE_FIELD(struct CastedSpellData, duration, SV_I32),
    SAVE_FIELD(struct CastedSpellData, caster_level, SV_U8),
    SAVE_FIELD(struct CastedSpellData, caster_owner, SV_I8),
);

SAVE_STRUCT(CreatureBattle, struct CreatureBattle,
    SAVE_FIELD(struct CreatureBattle, fighters_num, SV_U32),
    SAVE_FIELD(struct CreatureBattle, first_creatr, SV_U16),
    SAVE_FIELD(struct CreatureBattle, last_creatr, SV_U16),
);

SAVE_STRUCT(CreatureControl, struct CreatureControl,
    SAVE_FIELD(struct CreatureControl, index, SV_U16),
    SAVE_FIELD(struct CreatureControl, creature_control_flags, SV_U16),
    SAVE_FIELD(struct CreatureControl, creature_state_flags, SV_U8),
    SAVE_FIELD(struct CreatureControl, combat_flags, SV_U8),
    SAVE_FIELD(struct CreatureControl, wait_to_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, distance_to_destination, SV_I16),
    SAVE_ARRAY(struct CreatureControl, opponents_melee, SV_U16),
    SAVE_ARRAY(struct CreatureControl, opponents_ranged, SV_U16),
    SAVE_FIELD(struct CreatureControl, opponents_melee_count, SV_U8),
    SAVE_FIELD(struct CreatureControl, opponents_ranged_count, SV_U8),
    SAVE_FIELD(struct CreatureControl, players_prev_creature_idx, SV_U16),
    SAVE_FIELD(struct CreatureControl, players_next_creature_idx, SV_U16),
    SAVE_FIELD(struct CreatureControl, slap_turns, SV_U16),
    SAVE_FIELD(struct CreatureControl, exp_level, SV_U8),
    SAVE_FIELD(struct CreatureControl, exp_points, SV_I32),
    SAVE_FIELD(struct CreatureControl, prev_exp_points, SV_I32),
    SAVE_SUB(struct CreatureControl, moveto_pos, Coord3d),
    SAVE_FIELD(struct CreatureControl, hunger_level, SV_I32),
    SAVE_FIELD(struct CreatureControl, temple_cure_gameturn, SV_I32),
    SAVE_FIELD(struct CreatureControl, hunger_amount, SV_U8),
    SAVE_FIELD(struct CreatureControl, hunger_loss, SV_U8),
    SAVE_FIELD(struct CreatureControl, thought_bubble_last_turn_drawn, SV_I32),
    SAVE_FIELD(struct CreatureControl, thought_bubble_display_timer, SV_U8),
    SAVE_FIELD(struct CreatureControl, force_health_flower_displayed, SV_BOOL8),
    SAVE_FIELD(struct CreatureControl, force_health_flower_hidden, SV_BOOL8),
    SAVE_FIELD(struct CreatureControl, paydays_owed, SV_U8),
    SAVE_FIELD(struct CreatureControl, paydays_advanced, SV_I8),
    SAVE_FIELD(struct CreatureControl, annoy_untrained_turn, SV_I32),
    SAVE_FIELD(struct CreatureControl, last_roar_turn, SV_U32),
    SAVE_ARRAY(struct CreatureControl, annoyance_level, SV_I32),
    SAVE_FIELD(struct CreatureControl, mood_flags, SV_U8),
    SAVE_FIELD(struct CreatureControl, footstep_variant, SV_U8),
    SAVE_FIELD(struct CreatureControl, footstep_counter, SV_U8),
    SAVE_FIELD(struct CreatureControl, lair_room_id, SV_U16),
    SAVE_FIELD(struct CreatureControl, lairtng_idx, SV_U16),
    SAVE_FIELD(struct CreatureControl, dragtng_idx, SV_I16),
    SAVE_FIELD(struct CreatureControl, arming_thing_id, SV_U16),
    SAVE_FIELD(struct CreatureControl, pickup_object_id, SV_U16),
    SAVE_FIELD(struct CreatureControl, pickup_creature_id, SV_U16),
    SAVE_FIELD(struct CreatureControl, next_in_group, SV_U16),
    SAVE_FIELD(struct CreatureControl, prev_in_group, SV_U16),
    SAVE_FIELD(struct CreatureControl, group_leader_idx, SV_U16),
    SAVE_FIELD(struct CreatureControl, group_member_count, SV_U16),
    SAVE_FIELD(struct CreatureControl, last_work_room_id, SV_I16),
    SAVE_FIELD(struct CreatureControl, work_room_id, SV_I16),
    SAVE_FIELD(struct CreatureControl, target_room_id, SV_I16),
    SAVE_FIELD(struct CreatureControl, turns_at_job, SV_I32),
    SAVE_FIELD(struct CreatureControl, blocking_door_id, SV_I16),
    SAVE_FIELD(struct CreatureControl, move_flags, SV_U8),
    SAVE_FIELD(struct CreatureControl, cleanse_flags, SV_U32),
    SAVE_OPAQUE(struct CreatureControl, digger, "union:digger", (uint32_t)(offsetof(struct CreatureControl, party) - offsetof(struct CreatureControl, digger))),  /* union */
    SAVE_FIELD(struct CreatureControl, party.objective, SV_U8),
    SAVE_FIELD(struct CreatureControl, party.original_objective, SV_U8),
    SAVE_FIELD(struct CreatureControl, party.target_plyr_idx, SV_I8),
    SAVE_FIELD(struct CreatureControl, party.player_broken_into_flags, SV_U16),
    SAVE_FIELD(struct CreatureControl, party.tunnel_steps_counter, SV_I32),
    SAVE_FIELD(struct CreatureControl, party.tunnel_dig_direction, SV_U8),
    SAVE_ARRAY(struct CreatureControl, party.member_pos_stl, SV_I32),
    SAVE_FIELD(struct CreatureControl, patrol.countdown, SV_I16),
    SAVE_SUB(struct CreatureControl, patrol.pos, Coord3d),
    SAVE_OPAQUE(struct CreatureControl, tortured, "union:tortured", (uint32_t)(offsetof(struct CreatureControl, fight_til_death) - offsetof(struct CreatureControl, tortured))),  /* union */
    SAVE_FIELD(struct CreatureControl, fight_til_death, SV_U8),
    SAVE_FIELD(struct CreatureControl, fighting_at_same_position, SV_BOOL8),
    SAVE_FIELD(struct CreatureControl, called_to_arms, SV_BOOL8),
    SAVE_FIELD(struct CreatureControl, exp_level_up, SV_BOOL8),
    SAVE_FIELD(struct CreatureControl, stateblock_flags, SV_U8),
    SAVE_FIELD(struct CreatureControl, spell_flags, SV_U32),
    SAVE_FIELD(struct CreatureControl, force_visible, SV_I16),
    SAVE_FIELD(struct CreatureControl, frozen_on_hit, SV_U8),
    SAVE_FIELD(struct CreatureControl, last_piss_turn, SV_I32),
    SAVE_FIELD(struct CreatureControl, disease_caster_plyridx, SV_U8),
    SAVE_FIELD(struct CreatureControl, teleport_x, SV_I32),
    SAVE_FIELD(struct CreatureControl, teleport_y, SV_I32),
    SAVE_FIELD(struct CreatureControl, corpse_to_piss_on, SV_U16),
    SAVE_SUB(struct CreatureControl, moveaccel, CoordDelta3d),
    SAVE_FIELD(struct CreatureControl, bloody_footsteps_turns, SV_U8),
    SAVE_FIELD(struct CreatureControl, kills_num, SV_I16),
    SAVE_FIELD(struct CreatureControl, kills_num_allied, SV_I16),
    SAVE_FIELD(struct CreatureControl, kills_num_enemy, SV_I16),
    SAVE_FIELD(struct CreatureControl, max_speed, SV_I16),
    SAVE_FIELD(struct CreatureControl, max_health, SV_I32),
    SAVE_FIELD(struct CreatureControl, move_speed, SV_I16),
    SAVE_FIELD(struct CreatureControl, orthogn_speed, SV_I16),
    SAVE_FIELD(struct CreatureControl, roll, SV_I16),
    SAVE_FIELD(struct CreatureControl, anim_time, SV_U32),
    SAVE_FIELD_EX(struct CreatureControl, instance_id, SV_I16, .flags = 0, .name_domain = SND_Instance),
    SAVE_FIELD(struct CreatureControl, inst_repeat, SV_BOOL8),
    SAVE_FIELD(struct CreatureControl, inst_turn, SV_U16),
    SAVE_FIELD(struct CreatureControl, inst_action_turns, SV_U16),
    SAVE_FIELD(struct CreatureControl, inst_total_turns, SV_U16),
    SAVE_FIELD(struct CreatureControl, targtng_idx, SV_U16),
    SAVE_FIELD(struct CreatureControl, targtstl_x, SV_I32),
    SAVE_FIELD(struct CreatureControl, targtstl_y, SV_I32),
    SAVE_ARRAY(struct CreatureControl, instance_use_turn, SV_U32),
    SAVE_ARRAY(struct CreatureControl, instance_available, SV_BOOL8),
    SAVE_FIELD(struct CreatureControl, instance_anim_step_turns, SV_U16),
    SAVE_FIELD(struct CreatureControl, collided_door_subtile, SV_I32),
    SAVE_FIELD(struct CreatureControl, fighting_player_idx, SV_I8),
    SAVE_FIELD(struct CreatureControl, shot_model, SV_I16),
    SAVE_SUB_ARRAY(struct CreatureControl, casted_spells, CastedSpellData),
    SAVE_FIELD_EX(struct CreatureControl, active_instance_id, SV_I16, .flags = 0, .name_domain = SND_Instance),
    SAVE_SUB(struct CreatureControl, navi, Navigation),
    SAVE_SUB(struct CreatureControl, arid, Ariadne),
    SAVE_FIELD(struct CreatureControl, active_state_bkp, SV_U8),
    SAVE_FIELD(struct CreatureControl, continue_state_bkp, SV_U8),
    SAVE_FIELD(struct CreatureControl, cowers_from_slap_turns, SV_U8),
    SAVE_FIELD(struct CreatureControl, conscious_back_turns, SV_I16),
    SAVE_FIELD(struct CreatureControl, countdown, SV_I16),
    SAVE_FIELD(struct CreatureControl, damage_wall_coords, SV_I32),
    SAVE_FIELD(struct CreatureControl, joining_age, SV_U8),
    SAVE_FIELD(struct CreatureControl, blood_type, SV_U8),
    SAVE_STRING(struct CreatureControl, creature_name),  /* plain-char */
    SAVE_SUB(struct CreatureControl, flee_pos, Coord3d),
    SAVE_FIELD(struct CreatureControl, flee_start_turn, SV_I32),
    SAVE_SUB_ARRAY(struct CreatureControl, followers_pos, MemberPos),
    SAVE_FIELD(struct CreatureControl, next_in_room, SV_U16),
    SAVE_FIELD(struct CreatureControl, prev_in_room, SV_U16),
    SAVE_FIELD(struct CreatureControl, spell_aura, SV_I16),
    SAVE_FIELD(struct CreatureControl, spell_aura_duration, SV_I32),
    SAVE_FIELD(struct CreatureControl, job_assigned, SV_U16),
    SAVE_ARRAY(struct CreatureControl, spell_thing_index_armour, SV_U16),
    SAVE_ARRAY(struct CreatureControl, spell_thing_index_disease, SV_U16),
    SAVE_FIELD(struct CreatureControl, shot_shift_x, SV_I16),
    SAVE_FIELD(struct CreatureControl, shot_shift_y, SV_I16),
    SAVE_FIELD(struct CreatureControl, shot_shift_z, SV_I16),
    SAVE_FIELD(struct CreatureControl, tasks_check_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, wander_around_check_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, job_primary_check_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, job_secondary_check_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, healing_sleep_check_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, garden_eat_check_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, temple_pray_check_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, sulking_sleep_check_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, job_assigned_check_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, disease_start_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, armageddon_teleport_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, battle_prev_creatr, SV_U16),
    SAVE_FIELD(struct CreatureControl, battle_next_creatr, SV_U16),
    SAVE_FIELD(struct CreatureControl, battle_id, SV_U8),
    SAVE_FIELD(struct CreatureControl, alarm_stl_x, SV_I32),
    SAVE_FIELD(struct CreatureControl, alarm_stl_y, SV_I32),
    SAVE_FIELD(struct CreatureControl, alarm_over_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, lava_escape_since, SV_U32),
    SAVE_FIELD(struct CreatureControl, stopped_for_hand_turns, SV_U8),
    SAVE_FIELD(struct CreatureControl, following_leader_since, SV_I32),
    SAVE_FIELD(struct CreatureControl, follow_leader_fails, SV_U8),
    SAVE_FIELD(struct CreatureControl, dropped_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, timebomb_countdown, SV_U32),
    SAVE_FIELD(struct CreatureControl, timebomb_countdown_id, SV_U16),
    SAVE_FIELD(struct CreatureControl, timebomb_target_id, SV_U16),
    SAVE_FIELD(struct CreatureControl, unsummon_turn, SV_U32),
    SAVE_FIELD(struct CreatureControl, summoner_idx, SV_U16),
    SAVE_FIELD_EX(struct CreatureControl, summon_spl_idx, SV_U16, .flags = 0, .name_domain = SND_Spell),
    SAVE_ARRAY(struct CreatureControl, familiar_idx, SV_U16),
    SAVE_FIELD_EX(struct CreatureControl, active_disease_spell, SV_U16, .flags = 0, .name_domain = SND_Spell),
    SAVE_FIELD_EX(struct CreatureControl, active_teleport_spell, SV_U16, .flags = 0, .name_domain = SND_Spell),
    SAVE_FIELD_EX(struct CreatureControl, active_timebomb_spell, SV_U16, .flags = 0, .name_domain = SND_Spell),
    SAVE_FIELD(struct CreatureControl, vertical_speed, SV_I16),
    SAVE_FIELD(struct CreatureControl, hand_blocked_turns, SV_I32),
);

SAVE_STRUCT(MemberPos, struct MemberPos,
    SAVE_FIELD(struct MemberPos, stl_num, SV_I32),
    SAVE_FIELD(struct MemberPos, flags, SV_U8),
);

SAVE_STRUCT(Navigation, struct Navigation,
    SAVE_FIELD(struct Navigation, navstate, SV_U8),
    SAVE_FIELD(struct Navigation, side, SV_U8),
    SAVE_FIELD(struct Navigation, wallhug_retry_counter, SV_U8),
    SAVE_FIELD(struct Navigation, wallhug_state, SV_U8),
    SAVE_FIELD(struct Navigation, push_counter, SV_U8),
    SAVE_FIELD(struct Navigation, dist_to_final_pos, SV_I32),
    SAVE_FIELD(struct Navigation, distance_to_next_pos, SV_I32),
    SAVE_FIELD(struct Navigation, angle, SV_I32),
    SAVE_FIELD(struct Navigation, first_colliding_block, SV_I32),
    SAVE_FIELD(struct Navigation, second_colliding_block, SV_I32),
    SAVE_ARRAY(struct Navigation, owner_flags, SV_U16),
    SAVE_SUB(struct Navigation, pos_next, Coord3d),
    SAVE_SUB(struct Navigation, pos_final, Coord3d),
);

SAVE_STRUCT(StructureList, struct StructureList,
    SAVE_FIELD(struct StructureList, count, SV_U32),
    SAVE_FIELD(struct StructureList, index, SV_U32),
);

SAVE_UNION_SELECTED_DEF(Thing_u_valuable, "thing_arm",
    SAVE_UNION_MEMBER_NONE("none", .values = { STA_None }, .nvalues = 1),
    SAVE_UNION_MEMBER_SHARED("object_bytes", Thing_heart, "custom_box,call_to_arms_flag,heart,hero_gate,lightning", .values = { STA_ObjectBytes }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("valuable", Thing_valuable, .values = { STA_Valuable }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("food", Thing_food, .values = { STA_Food }, .nvalues = 1),
    SAVE_UNION_MEMBER_SHARED("lair", Thing_lair, "lair,torturer", .values = { STA_Lair }, .nvalues = 1),
    SAVE_UNION_MEMBER_SHARED("armor", Thing_armor, "armor,disease", .values = { STA_Armor }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("roomflag", Thing_roomflag, .values = { STA_RoomFlag }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("shot", Thing_shot, .values = { STA_Shot }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("shot_lizard", Thing_shot_lizard, .values = { STA_ShotLizard }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("corpse", Thing_corpse, .values = { STA_Corpse }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("creature", Thing_creature, .values = { STA_Creature }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("shot_effect", Thing_shot_effect, .values = { STA_ShotEffect }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("price_effect", Thing_price_effect, .values = { STA_PriceEffect }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("effect_generator", Thing_effect_generator, .values = { STA_EffectGenerator }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("trap", Thing_trap, .values = { STA_Trap }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("door", Thing_door, .values = { STA_Door }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("cave_in", Thing_cave_in, .values = { STA_CaveIn }, .nvalues = 1),
    SAVE_UNION_MEMBER_RAW("any", (uint32_t)(offsetof(struct Thing, model) - offsetof(struct Thing, valuable)), "*", .is_default = 1)
);

SAVE_STRUCT(Thing_armor, struct Thing,
    SAVE_FIELD(struct Thing, armor.belongs_to, SV_I16),
    SAVE_FIELD(struct Thing, armor.shspeed, SV_U8),
);

SAVE_STRUCT(Thing_food, struct Thing,
    SAVE_FIELD(struct Thing, food.life_remaining, SV_I16),
    SAVE_FIELD(struct Thing, food.freshness_state, SV_I8),
    SAVE_FIELD(struct Thing, food.possession_startup_timer, SV_U8),
    SAVE_FIELD(struct Thing, food.some_chicken_was_sacrificed, SV_BOOL8),
    SAVE_FIELD(struct Thing, food.angle, SV_U16),
);

SAVE_STRUCT(Thing_heart, struct Thing,
    SAVE_FIELD(struct Thing, heart.countdown_UNUSED, SV_U8),
    SAVE_FIELD(struct Thing, heart.beat_direction, SV_U8),
);

SAVE_STRUCT(Thing_lair, struct Thing,
    SAVE_FIELD(struct Thing, lair.belongs_to, SV_I16),
    SAVE_FIELD(struct Thing, lair.cssize, SV_I16),
    SAVE_FIELD(struct Thing, lair.spr_size, SV_I16),
);

SAVE_STRUCT(Thing_price_effect, struct Thing,
    SAVE_FIELD(struct Thing, price_effect.number, SV_I32),
);

SAVE_STRUCT(Thing_roomflag, struct Thing,
    SAVE_FIELD(struct Thing, roomflag.room_idx, SV_I32),
    SAVE_FIELD(struct Thing, roomflag.last_turn_drawn, SV_I32),
    SAVE_FIELD(struct Thing, roomflag.display_timer, SV_U8),
);

SAVE_STRUCT(Thing_shot, struct Thing,
    SAVE_FIELD(struct Thing, shot.dexterity, SV_U8),
    SAVE_FIELD(struct Thing, shot.damage, SV_I16),
    SAVE_FIELD(struct Thing, shot.hit_type, SV_U8),
    SAVE_FIELD(struct Thing, shot.target_idx, SV_I16),
    SAVE_FIELD(struct Thing, shot.shot_level, SV_U8),
    SAVE_SUB(struct Thing, shot.originpos, Coord3d),
    SAVE_FIELD(struct Thing, shot.num_wind_affected, SV_I32),
    SAVE_ARRAY(struct Thing, shot.wind_affected_creature, SV_U16),
);

SAVE_STRUCT(Thing_shot_effect, struct Thing,
    SAVE_FIELD(struct Thing, shot_effect.parent_class_id, SV_I32),
    SAVE_FIELD(struct Thing, shot_effect.parent_model, SV_I16),
    SAVE_FIELD(struct Thing, shot_effect.hit_type, SV_U8),
);

SAVE_STRUCT(Thing_shot_lizard, struct Thing,
    SAVE_FIELD(struct Thing, shot_lizard.x, SV_I32),
    SAVE_FIELD(struct Thing, shot_lizard.target_idx, SV_I16),
    SAVE_FIELD(struct Thing, shot_lizard.posint, SV_U8),
    SAVE_FIELD(struct Thing, shot_lizard.range, SV_U8),
);

SAVE_STRUCT(Thing_valuable, struct Thing,
    SAVE_FIELD(struct Thing, valuable.gold_stored, SV_I32),
    SAVE_FIELD(struct Thing, valuable.unusedparam, SV_I16),
);

SAVE_STRUCT(Thing, struct Thing,
    SAVE_FIELD(struct Thing, alloc_flags, SV_U8),
    SAVE_FIELD(struct Thing, state_flags, SV_U8),
    SAVE_FIELD(struct Thing, next_on_mapblk, SV_U16),
    SAVE_FIELD(struct Thing, prev_on_mapblk, SV_U16),
    SAVE_FIELD(struct Thing, owner, SV_U8),
    SAVE_FIELD(struct Thing, active_state, SV_U8),
    SAVE_FIELD(struct Thing, continue_state, SV_U8),
    SAVE_FIELD(struct Thing, creation_turn, SV_I32),
    SAVE_SUB(struct Thing, mappos, Coord3d),
    SAVE_UNION(struct Thing, valuable, "union:valuable", (uint32_t)(offsetof(struct Thing, model) - offsetof(struct Thing, valuable)), Thing_u_valuable),  /* union */
    SAVE_FIELD_EX(struct Thing, model, SV_I16, .flags = 0, .name_domain = SND_ByThingClass),
    SAVE_FIELD(struct Thing, index, SV_U16),
    SAVE_FIELD(struct Thing, parent_idx, SV_I16),
    SAVE_FIELD(struct Thing, class_id, SV_U8),
    SAVE_FIELD(struct Thing, fall_acceleration, SV_U8),
    SAVE_FIELD(struct Thing, bounce_angle, SV_U8),
    SAVE_FIELD(struct Thing, abyss_fall_sound_delay, SV_U8),
    SAVE_FIELD(struct Thing, inertia_floor, SV_I16),
    SAVE_FIELD(struct Thing, inertia_air, SV_I16),
    SAVE_FIELD(struct Thing, movement_flags, SV_U16),
    SAVE_SUB(struct Thing, veloc_push_once, CoordDelta3d),
    SAVE_SUB(struct Thing, veloc_base, CoordDelta3d),
    SAVE_SUB(struct Thing, veloc_push_add, CoordDelta3d),
    SAVE_SUB(struct Thing, velocity, CoordDelta3d),
    SAVE_FIELD(struct Thing, anim_speed, SV_I16),
    SAVE_FIELD(struct Thing, anim_time, SV_I32),
    SAVE_FIELD(struct Thing, anim_sprite, SV_U16),
    SAVE_FIELD(struct Thing, sprite_size, SV_U16),
    SAVE_FIELD(struct Thing, current_frame, SV_U8),
    SAVE_FIELD(struct Thing, max_frames, SV_U8),
    SAVE_FIELD(struct Thing, transformation_speed, SV_I8),
    SAVE_FIELD(struct Thing, sprite_size_min, SV_U16),
    SAVE_FIELD(struct Thing, sprite_size_max, SV_U16),
    SAVE_FIELD(struct Thing, rendering_flags, SV_U8),
    SAVE_FIELD(struct Thing, draw_class, SV_U8),
    SAVE_FIELD(struct Thing, size_change, SV_U8),
    SAVE_FIELD(struct Thing, tint_colour, SV_U8),
    SAVE_FIELD(struct Thing, move_angle_xy, SV_I16),
    SAVE_FIELD(struct Thing, move_angle_z, SV_I16),
    SAVE_FIELD(struct Thing, clipbox_size_xy, SV_U16),
    SAVE_FIELD(struct Thing, clipbox_size_z, SV_U16),
    SAVE_FIELD(struct Thing, solid_size_xy, SV_U16),
    SAVE_FIELD(struct Thing, solid_size_z, SV_U16),
    SAVE_FIELD(struct Thing, health, SV_I32),
    SAVE_FIELD(struct Thing, floor_height, SV_U16),
    SAVE_FIELD(struct Thing, light_id, SV_U16),
    SAVE_FIELD(struct Thing, ccontrol_idx, SV_U16),
    SAVE_FIELD(struct Thing, snd_emitter_id, SV_U8),
    SAVE_FIELD(struct Thing, next_of_class, SV_I16),
    SAVE_FIELD(struct Thing, prev_of_class, SV_I16),
    SAVE_FIELD(struct Thing, flags, SV_U32),
    SAVE_FIELD(struct Thing, last_turn_drawn, SV_U32),
    SAVE_FIELD(struct Thing, last_turn_damaged, SV_U32),
    SAVE_FIELD(struct Thing, last_turn_pushed, SV_U32),
    SAVE_FIELD(struct Thing, pushed_by_player, SV_I8),
    SAVE_FIELD(struct Thing, previous_floor_height, SV_U16),
    SAVE_SUB(struct Thing, previous_mappos, Coord3d),
    SAVE_FIELD(struct Thing, random_seed, SV_U32),
    SAVE_FIELD(struct Thing, holding_player, SV_I8),
);

SAVE_STRUCT(Thing_cave_in, struct Thing,
    SAVE_FIELD(struct Thing, cave_in.x, SV_U8),
    SAVE_FIELD(struct Thing, cave_in.y, SV_U8),
    SAVE_FIELD(struct Thing, cave_in.time, SV_I16),
    SAVE_FIELD(struct Thing, cave_in.model, SV_I16),
);

SAVE_STRUCT(Thing_corpse, struct Thing,
    SAVE_FIELD(struct Thing, corpse.exp_level, SV_U8),
    SAVE_FIELD(struct Thing, corpse.laid_to_rest, SV_U8),
);

SAVE_STRUCT(Thing_creature, struct Thing,
    SAVE_FIELD(struct Thing, creature.gold_carried, SV_I32),
    SAVE_FIELD(struct Thing, creature.health_bar_turns, SV_I16),
    SAVE_FIELD(struct Thing, creature.volley_repeat, SV_I16),
    SAVE_FIELD(struct Thing, creature.volley_fire, SV_BOOL8),
);

SAVE_STRUCT(Thing_door, struct Thing,
    SAVE_FIELD(struct Thing, door.orientation, SV_I16),
    SAVE_FIELD(struct Thing, door.opening_counter, SV_U8),
    SAVE_FIELD(struct Thing, door.closing_counter, SV_I16),
    SAVE_FIELD(struct Thing, door.is_locked, SV_U8),
    SAVE_FIELD(struct Thing, door.revealed, SV_U16),
);

SAVE_STRUCT(Thing_effect_generator, struct Thing,
    SAVE_FIELD(struct Thing, effect_generator.range, SV_I16),
    SAVE_FIELD(struct Thing, effect_generator.generation_delay, SV_I32),
);

SAVE_STRUCT(Thing_trap, struct Thing,
    SAVE_FIELD(struct Thing, trap.num_shots, SV_U8),
    SAVE_FIELD(struct Thing, trap.revealed, SV_U8),
    SAVE_FIELD(struct Thing, trap.wait_for_rearm, SV_BOOL8),
    SAVE_FIELD(struct Thing, trap.volley_fire, SV_BOOL8),
    SAVE_FIELD(struct Thing, trap.rearm_turn, SV_U32),
    SAVE_FIELD(struct Thing, trap.shooting_finished_turn, SV_U32),
    SAVE_FIELD(struct Thing, trap.volley_repeat, SV_I16),
    SAVE_FIELD(struct Thing, trap.volley_delay, SV_U16),
    SAVE_FIELD(struct Thing, trap.firing_at, SV_U16),
    SAVE_FIELD(struct Thing, trap.flag_number, SV_U8),
);
