/** @file schema_dungeon.c
 *     Field tables for saved structs.
 */
#include "pre_inc.h"
#include "kfx/save/SaveTypes.h"
#include "game_legacy.h"
#include "game_merge.h"
#include "packets.h"
#include "config_campaigns.h"
#include "front_network.h"
#include "post_inc.h"
#include "kfx/save/core/save_schema.h"
#include "kfx/save/core/schema/save_tables_decl.h"

SAVE_STRUCT(Bookmark, struct Bookmark,
    SAVE_FIELD(struct Bookmark, x, SV_I32),
    SAVE_FIELD(struct Bookmark, y, SV_I32),
    SAVE_FIELD(struct Bookmark, flags, SV_U8),
);

SAVE_STRUCT(BoxInfo, struct BoxInfo,
    SAVE_ARRAY(struct BoxInfo, activated, SV_U16),
);

SAVE_STRUCT(CheatSelection, struct CheatSelection,
    SAVE_FIELD(struct CheatSelection, chosen_terrain_kind, SV_U8),
    SAVE_FIELD(struct CheatSelection, chosen_player, SV_I8),
    SAVE_FIELD(struct CheatSelection, chosen_creature_kind, SV_U8),
    SAVE_FIELD(struct CheatSelection, chosen_hero_kind, SV_U8),
    SAVE_FIELD(struct CheatSelection, chosen_experience_level, SV_U8),
);

SAVE_STRUCT(Computer2, struct Computer2,
    SAVE_FIELD(struct Computer2, task_state, SV_I32),
    SAVE_FIELD(struct Computer2, gameturn_delay, SV_U32),
    SAVE_FIELD(struct Computer2, gameturn_wait, SV_U32),
    SAVE_FIELD(struct Computer2, action_status_flag, SV_U32),
    SAVE_FIELD(struct Computer2, tasks_did, SV_U32),
    SAVE_FIELD(struct Computer2, processes_time, SV_U32),
    SAVE_FIELD(struct Computer2, click_rate, SV_U32),
    SAVE_FIELD(struct Computer2, dig_stack_size, SV_I32),
    SAVE_FIELD(struct Computer2, sim_before_dig, SV_U32),
    SAVE_RUNTIME(struct Computer2, dungeon),  /* pointer */
    SAVE_FIELD(struct Computer2, model, SV_U32),
    SAVE_FIELD(struct Computer2, turn_begin, SV_U32),
    SAVE_FIELD(struct Computer2, max_room_build_tasks, SV_U32),
    SAVE_FIELD(struct Computer2, task_delay, SV_U32),
    SAVE_SUB_ARRAY(struct Computer2, processes, ComputerProcess),
    SAVE_SUB_ARRAY(struct Computer2, checks, ComputerCheck),
    SAVE_SUB_ARRAY(struct Computer2, events, ComputerEvent),
    SAVE_SUB_ARRAY(struct Computer2, opponent_relations, OpponentRelation),
    SAVE_SUB_ARRAY(struct Computer2, trap_locations, Coord3d),
    SAVE_ARRAY(struct Computer2, soe_targets, SV_U32),
    SAVE_FIELD(struct Computer2, ongoing_process, SV_I16),
    SAVE_FIELD(struct Computer2, task_idx, SV_I16),
    SAVE_FIELD(struct Computer2, held_thing_idx, SV_I16),
);

SAVE_STRUCT(ComputerCheck, struct ComputerCheck,
    SAVE_STRING(struct ComputerCheck, name),  /* plain-char */
    SAVE_STRING(struct ComputerCheck, mnemonic),  /* plain-char */
    SAVE_FIELD(struct ComputerCheck, flags, SV_U32),
    SAVE_FIELD(struct ComputerCheck, turns_interval, SV_I32),
    SAVE_FIELD(struct ComputerCheck, func, SV_I16),
    SAVE_FIELD(struct ComputerCheck, primary_parameter, SV_I32),
    SAVE_FIELD(struct ComputerCheck, secondary_parameter, SV_I32),
    SAVE_FIELD(struct ComputerCheck, tertiary_parameter, SV_I32),
    SAVE_FIELD(struct ComputerCheck, last_run_turn, SV_I32),
);

SAVE_STRUCT(ComputerDig, struct ComputerDig,
    SAVE_SUB(struct ComputerDig, pos_E, Coord3d),
    SAVE_SUB(struct ComputerDig, pos_dest, Coord3d),
    SAVE_SUB(struct ComputerDig, pos_begin, Coord3d),
    SAVE_SUB(struct ComputerDig, pos_next, Coord3d),
    SAVE_FIELD(struct ComputerDig, distance, SV_I32),
    SAVE_FIELD(struct ComputerDig, hug_side, SV_U8),
    SAVE_FIELD(struct ComputerDig, direction_around, SV_I8),
    SAVE_FIELD(struct ComputerDig, action_success_flag, SV_U32),
    SAVE_FIELD(struct ComputerDig, number_of_failed_actions, SV_I32),
    SAVE_FIELD(struct ComputerDig, last_backwards_step_stl_x, SV_I32),
    SAVE_FIELD(struct ComputerDig, last_backwards_step_stl_y, SV_I32),
    SAVE_FIELD(struct ComputerDig, calls_count, SV_I32),
    SAVE_FIELD(struct ComputerDig, valuable_slabs_tagged, SV_I32),
    SAVE_FIELD(struct ComputerDig, room.area, SV_I32),
    SAVE_FIELD(struct ComputerDig, room.slabs_processed, SV_I32),
    SAVE_FIELD(struct ComputerDig, room.spiral.forward_direction, SV_I8),
    SAVE_FIELD(struct ComputerDig, room.spiral.turns_made, SV_I32),
    SAVE_FIELD(struct ComputerDig, room.spiral.steps_to_take_before_turning, SV_I32),
    SAVE_FIELD(struct ComputerDig, room.spiral.steps_remaining_before_turn, SV_I32),
);

SAVE_STRUCT(ComputerEvent, struct ComputerEvent,
    SAVE_STRING(struct ComputerEvent, name),  /* plain-char */
    SAVE_STRING(struct ComputerEvent, mnemonic),  /* plain-char */
    SAVE_FIELD(struct ComputerEvent, cetype, SV_U32),
    SAVE_FIELD(struct ComputerEvent, mevent_kind, SV_U32),
    SAVE_FIELD(struct ComputerEvent, func_event, SV_I16),
    SAVE_FIELD(struct ComputerEvent, func_test, SV_I16),
    SAVE_FIELD(struct ComputerEvent, test_interval, SV_I32),
    SAVE_FIELD(struct ComputerEvent, process, SV_U8),
    SAVE_FIELD(struct ComputerEvent, primary_parameter, SV_I32),
    SAVE_FIELD(struct ComputerEvent, secondary_parameter, SV_I32),
    SAVE_FIELD(struct ComputerEvent, tertiary_parameter, SV_I32),
    SAVE_FIELD(struct ComputerEvent, last_test_gameturn, SV_I32),
);

SAVE_STRUCT(ComputerProcess, struct ComputerProcess,
    SAVE_STRING(struct ComputerProcess, name),  /* plain-char */
    SAVE_STRING(struct ComputerProcess, mnemonic),  /* plain-char */
    SAVE_FIELD(struct ComputerProcess, priority, SV_I32),
    SAVE_FIELD(struct ComputerProcess, process_configuration_value_2, SV_I32),
    SAVE_FIELD(struct ComputerProcess, process_configuration_value_3, SV_I32),
    SAVE_FIELD(struct ComputerProcess, process_configuration_value_4, SV_I32),
    SAVE_FIELD(struct ComputerProcess, process_configuration_value_5, SV_I32),
    SAVE_FIELD(struct ComputerProcess, func_check, SV_I16),
    SAVE_FIELD(struct ComputerProcess, func_setup, SV_I16),
    SAVE_FIELD(struct ComputerProcess, func_task, SV_I16),
    SAVE_FIELD(struct ComputerProcess, func_complete, SV_I16),
    SAVE_FIELD(struct ComputerProcess, func_pause, SV_I16),
    SAVE_FIELD(struct ComputerProcess, parent, SV_U8),
    SAVE_FIELD(struct ComputerProcess, process_parameter_1, SV_U32),
    SAVE_FIELD(struct ComputerProcess, process_parameter_2, SV_U32),
    SAVE_FIELD(struct ComputerProcess, process_parameter_3, SV_U32),
    SAVE_FIELD(struct ComputerProcess, last_run_turn, SV_U32),
    SAVE_FIELD(struct ComputerProcess, process_parameter_5, SV_I32),
    SAVE_FIELD(struct ComputerProcess, flags, SV_U32),
);

SAVE_UNION_DEF(ComputerTask_u_sell_traps_doors, "ttype",
    SAVE_UNION_MEMBER_NONE("none", .values = { CTT_None }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("sell_traps_doors", ComputerTask_sell_traps_doors, .values = { CTT_SellTrapsAndDoors }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("move_gold", ComputerTask_move_gold, .values = { CTT_MoveGoldToTreasury }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("magic_cta", ComputerTask_magic_cta, .values = { CTT_MagicCallToArms }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("attack_magic", ComputerTask_attack_magic, .values = { CTT_AttackMagic, CTT_MagicSpeedUp }, .nvalues = 2),
    SAVE_UNION_MEMBER_SUB("slap_diggers", ComputerTask_slap_imps, .values = { CTT_SlapDiggers }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("sacrifice_diggers", ComputerTask_sacrifice_imp, .values = { CTT_SacrificeDiggers }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("move_to_room", ComputerTask_move_to_room, .values = { CTT_MoveCreatureToRoom }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("move_to_defend", ComputerTask_move_to_defend, .values = { CTT_MoveCreaturesToDefend }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("move_to_pos", ComputerTask_move_to_pos, .values = { CTT_MoveCreatureToPos }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("pickup_for_attack", ComputerTask_pickup_for_attack, .values = { CTT_PickupForAttack }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("dig_to_room", ComputerTask_dig_to_room, .values = { CTT_DigToEntrance }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("dig_to_gold", ComputerTask_dig_to_gold, .values = { CTT_DigToGold }, .nvalues = 1),
    SAVE_UNION_MEMBER_SUB("dig_somewhere", ComputerTask_dig_somewhere, .values = { CTT_DigToAttack, CTT_DigToNeutral }, .nvalues = 2),
    SAVE_UNION_MEMBER_SUB("create_room", ComputerTask_create_room, .values = { CTT_DigRoomPassage, CTT_DigRoom, CTT_CheckRoomDug, CTT_PlaceRoom }, .nvalues = 4),
    SAVE_UNION_MEMBER_RAW("any", (uint32_t)(offsetof(struct ComputerTask, cproc_idx) - offsetof(struct ComputerTask, sell_traps_doors)), "*", .is_default = 1)
);

SAVE_STRUCT(ComputerTask, struct ComputerTask,
    SAVE_FIELD(struct ComputerTask, flags, SV_U8),
    SAVE_FIELD(struct ComputerTask, task_state, SV_U8),
    SAVE_FIELD(struct ComputerTask, ttype, SV_U8),
    SAVE_FIELD(struct ComputerTask, ottype, SV_U8),
    SAVE_FIELD(struct ComputerTask, rkind, SV_U8),
    SAVE_FIELD(struct ComputerTask, created_turn, SV_I32),
    SAVE_SUB(struct ComputerTask, dig, ComputerDig),
    SAVE_FIELD(struct ComputerTask, lastrun_turn, SV_I32),
    SAVE_FIELD(struct ComputerTask, delay, SV_I32),
    SAVE_SUB(struct ComputerTask, new_room_pos, Coord3d),
    SAVE_SUB(struct ComputerTask, starting_position, Coord3d),
    SAVE_UNION(struct ComputerTask, sell_traps_doors, "union:sell_traps_doors", (uint32_t)(offsetof(struct ComputerTask, cproc_idx) - offsetof(struct ComputerTask, sell_traps_doors)), ComputerTask_u_sell_traps_doors),  /* union */
    SAVE_FIELD(struct ComputerTask, cproc_idx, SV_U16),
    SAVE_FIELD(struct ComputerTask, cta_duration, SV_I32),
    SAVE_FIELD(struct ComputerTask, next_task, SV_U16),
);

SAVE_STRUCT(ComputerTask_attack_magic, struct ComputerTask,
    SAVE_FIELD(struct ComputerTask, attack_magic.power_level, SV_U8),
    SAVE_FIELD(struct ComputerTask, attack_magic.target_thing_idx, SV_I16),
    SAVE_FIELD(struct ComputerTask, attack_magic.repeat_num, SV_I32),
    SAVE_FIELD(struct ComputerTask, attack_magic.gaction, SV_I32),
    SAVE_FIELD(struct ComputerTask, attack_magic.pwkind, SV_I32),
);

SAVE_STRUCT(ComputerTask_create_room, struct ComputerTask,
    SAVE_SUB(struct ComputerTask, create_room.startpos, Coord3d),
    SAVE_SUB(struct ComputerTask, create_room.endpos, Coord3d),
    SAVE_FIELD(struct ComputerTask, create_room.width, SV_I16),
    SAVE_FIELD(struct ComputerTask, create_room.height, SV_I16),
    SAVE_FIELD(struct ComputerTask, create_room.kind, SV_U8),
    SAVE_FIELD(struct ComputerTask, create_room.area, SV_I32),
);

SAVE_STRUCT(ComputerTask_dig_somewhere, struct ComputerTask,
    SAVE_SUB(struct ComputerTask, dig_somewhere.startpos, Coord3d),
    SAVE_SUB(struct ComputerTask, dig_somewhere.endpos, Coord3d),
    SAVE_FIELD(struct ComputerTask, dig_somewhere.target_plyr_idx, SV_I16),
);

SAVE_STRUCT(ComputerTask_dig_to_gold, struct ComputerTask,
    SAVE_SUB(struct ComputerTask, dig_to_gold.startpos, Coord3d),
    SAVE_SUB(struct ComputerTask, dig_to_gold.endpos, Coord3d),
    SAVE_FIELD(struct ComputerTask, dig_to_gold.target_lookup_idx, SV_I16),
    SAVE_FIELD(struct ComputerTask, dig_to_gold.slabs_dig_count, SV_I32),
);

SAVE_STRUCT(ComputerTask_dig_to_room, struct ComputerTask,
    SAVE_SUB(struct ComputerTask, dig_to_room.startpos, Coord3d),
    SAVE_SUB(struct ComputerTask, dig_to_room.endpos, Coord3d),
    SAVE_FIELD(struct ComputerTask, dig_to_room.target_room_idx, SV_I16),
    SAVE_FIELD(struct ComputerTask, dig_to_room.target_plyr_idx, SV_I16),
);

SAVE_STRUCT(ComputerTask_magic_cta, struct ComputerTask,
    SAVE_SUB(struct ComputerTask, magic_cta.target_pos, Coord3d),
    SAVE_FIELD(struct ComputerTask, magic_cta.repeat_num, SV_I32),
);

SAVE_STRUCT(ComputerTask_move_gold, struct ComputerTask,
    SAVE_FIELD(struct ComputerTask, move_gold.items_amount, SV_I32),
    SAVE_FIELD(struct ComputerTask, move_gold.room_idx, SV_I16),
    SAVE_FIELD(struct ComputerTask, move_gold.gold_gain, SV_I32),
    SAVE_FIELD(struct ComputerTask, move_gold.gold_gain_limit, SV_I32),
    SAVE_FIELD(struct ComputerTask, move_gold.total_money_limit, SV_I32),
);

SAVE_STRUCT(ComputerTask_sacrifice_imp, struct ComputerTask,
    SAVE_FIELD(struct ComputerTask, sacrifice_imp.max_level, SV_I32),
    SAVE_FIELD(struct ComputerTask, sacrifice_imp.digger_model_id, SV_I32),
    SAVE_FIELD(struct ComputerTask, sacrifice_imp.target_state, SV_U16),
);

SAVE_STRUCT(ComputerTask_slap_imps, struct ComputerTask,
    SAVE_FIELD(struct ComputerTask, slap_imps.skip_speed, SV_BOOL8),
);

SAVE_STRUCT(ComputerTask_move_to_defend, struct ComputerTask,
    SAVE_FIELD(struct ComputerTask, move_to_defend.evflags, SV_I32),
    SAVE_SUB(struct ComputerTask, move_to_defend.target_pos, Coord3d),
    SAVE_FIELD(struct ComputerTask, move_to_defend.repeat_num, SV_I32),
    SAVE_FIELD(struct ComputerTask, move_to_defend.target_state, SV_U16),
);

SAVE_STRUCT(ComputerTask_move_to_pos, struct ComputerTask,
    SAVE_FIELD(struct ComputerTask, move_to_pos.target_thing_idx, SV_I16),
    SAVE_SUB(struct ComputerTask, move_to_pos.target_pos, Coord3d),
    SAVE_FIELD(struct ComputerTask, move_to_pos.repeat_num, SV_I32),
    SAVE_FIELD(struct ComputerTask, move_to_pos.target_state, SV_U16),
);

SAVE_STRUCT(ComputerTask_move_to_room, struct ComputerTask,
    SAVE_FIELD(struct ComputerTask, move_to_room.room_idx1, SV_U16),
    SAVE_FIELD(struct ComputerTask, move_to_room.repeat_num, SV_I32),
    SAVE_FIELD(struct ComputerTask, move_to_room.room_idx2, SV_U16),
);

SAVE_STRUCT(ComputerTask_pickup_for_attack, struct ComputerTask,
    SAVE_SUB(struct ComputerTask, pickup_for_attack.target_pos, Coord3d),
    SAVE_FIELD(struct ComputerTask, pickup_for_attack.repeat_num, SV_I32),
    SAVE_FIELD(struct ComputerTask, pickup_for_attack.target_state, SV_U16),
);

SAVE_STRUCT(ComputerTask_sell_traps_doors, struct ComputerTask,
    SAVE_FIELD(struct ComputerTask, sell_traps_doors.items_amount, SV_I32),
    SAVE_FIELD(struct ComputerTask, sell_traps_doors.gold_gain, SV_I32),
    SAVE_FIELD(struct ComputerTask, sell_traps_doors.gold_gain_limit, SV_I32),
    SAVE_FIELD(struct ComputerTask, sell_traps_doors.total_money_limit, SV_I32),
    SAVE_FIELD(struct ComputerTask, sell_traps_doors.allow_deployed, SV_I16),
    SAVE_FIELD(struct ComputerTask, sell_traps_doors.sell_idx, SV_I32),
);

SAVE_STRUCT(CreaturePool, struct CreaturePool,
    SAVE_ARRAY(struct CreaturePool, crtr_kind, SV_I32),
    SAVE_FIELD(struct CreaturePool, is_empty, SV_U8),
);

SAVE_STRUCT(DiggerStack, struct DiggerStack,
    SAVE_FIELD(struct DiggerStack, stl_num, SV_I32),
    SAVE_FIELD(struct DiggerStack, task_type, SV_U16),
);

SAVE_STRUCT(Dungeon, struct Dungeon,
    SAVE_FIELD(struct Dungeon, dnheart_idx, SV_U16),
    SAVE_SUB(struct Dungeon, mappos, Coord3d),
    SAVE_FIELD(struct Dungeon, creature_tendencies, SV_U8),
    SAVE_FIELD(struct Dungeon, computer_enabled, SV_U8),
    SAVE_FIELD(struct Dungeon, creatr_list_start, SV_I16),
    SAVE_FIELD(struct Dungeon, digger_list_start, SV_I16),
    SAVE_ARRAY(struct Dungeon, summon_list, SV_U16),
    SAVE_FIELD(struct Dungeon, num_summon, SV_U16),
    SAVE_ARRAY(struct Dungeon, things_in_hand, SV_U16),
    SAVE_FIELD(struct Dungeon, num_things_in_hand, SV_U8),
    SAVE_ARRAY2(struct Dungeon, crmodel_state_type_count, SV_U16),
    SAVE_ARRAY2(struct Dungeon, guijob_all_creatrs_count, SV_U16),
    SAVE_ARRAY2(struct Dungeon, guijob_angry_creatrs_count, SV_U16),
    SAVE_FIELD(struct Dungeon, sight_casted_gameturn, SV_I32),
    SAVE_FIELD(struct Dungeon, sight_casted_thing_idx, SV_I16),
    SAVE_FIELD(struct Dungeon, sight_casted_power_level, SV_U8),
    SAVE_FIELD(struct Dungeon, sight_casted_stl_x, SV_I32),
    SAVE_FIELD(struct Dungeon, sight_casted_stl_y, SV_I32),
    SAVE_ARRAY2(struct Dungeon, soe_explored_flags, SV_U8),
    SAVE_FIELD(struct Dungeon, cta_stl_x, SV_I32),
    SAVE_FIELD(struct Dungeon, cta_stl_y, SV_I32),
    SAVE_FIELD(struct Dungeon, cta_power_level, SV_U8),
    SAVE_FIELD(struct Dungeon, cta_start_turn, SV_U32),
    SAVE_FIELD(struct Dungeon, cta_free, SV_BOOL8),
    SAVE_FIELD(struct Dungeon, must_obey_turn, SV_U32),
    SAVE_FIELD(struct Dungeon, hold_audience_cast_turn, SV_I32),
    SAVE_FIELD(struct Dungeon, scavenge_counters_turn, SV_I32),
    SAVE_ARRAY(struct Dungeon, creatures_scavenging, SV_U8),
    SAVE_ARRAY(struct Dungeon, creatures_praying, SV_U8),
    SAVE_FIELD(struct Dungeon, chickens_sacrificed, SV_U8),
    SAVE_FIELD(struct Dungeon, gold_piles_sacrificed, SV_U8),
    SAVE_ARRAY(struct Dungeon, creature_sacrifice, SV_U8),
    SAVE_ARRAY(struct Dungeon, creature_sacrifice_exp, SV_U8),
    SAVE_FIELD(struct Dungeon, num_active_diggers, SV_U16),
    SAVE_FIELD(struct Dungeon, num_active_creatrs, SV_U16),
    SAVE_ARRAY(struct Dungeon, owned_creatures_of_model, SV_U16),
    SAVE_FIELD(struct Dungeon, total_rooms, SV_U8),
    SAVE_FIELD(struct Dungeon, total_doors, SV_U16),
    SAVE_FIELD(struct Dungeon, total_area, SV_U16),
    SAVE_FIELD(struct Dungeon, total_creatures_left, SV_U16),
    SAVE_FIELD(struct Dungeon, doors_destroyed, SV_I32),
    SAVE_FIELD(struct Dungeon, room_manage_area, SV_I16),
    SAVE_ARRAY(struct Dungeon, creatures_scavenged, SV_I16),
    SAVE_FIELD(struct Dungeon, creatures_scavenge_gain, SV_I16),
    SAVE_FIELD(struct Dungeon, creatures_scavenge_lost, SV_I16),
    SAVE_ARRAY(struct Dungeon, scavenge_turn_points, SV_I32),
    SAVE_ARRAY(struct Dungeon, scavenge_targets, SV_I16),
    SAVE_ARRAY(struct Dungeon, creature_max_level, SV_U8),
    SAVE_FIELD(struct Dungeon, creatures_annoyed, SV_U16),
    SAVE_FIELD(struct Dungeon, battles_lost, SV_U16),
    SAVE_FIELD(struct Dungeon, battles_won, SV_U16),
    SAVE_FIELD(struct Dungeon, rooms_destroyed, SV_U16),
    SAVE_FIELD(struct Dungeon, spells_stolen, SV_U16),
    SAVE_FIELD(struct Dungeon, times_broken_into, SV_U16),
    SAVE_FIELD(struct Dungeon, gold_pots_stolen, SV_U16),
    SAVE_FIELD(struct Dungeon, last_entrance_generation_gameturn, SV_I32),
    SAVE_FIELD(struct Dungeon, turns_between_entrance_generation, SV_I32),
    SAVE_FIELD(struct Dungeon, last_research_complete_gameturn, SV_I32),
    SAVE_FIELD(struct Dungeon, manage_score, SV_I32),
    SAVE_FIELD(struct Dungeon, total_score, SV_I32),
    SAVE_FIELD(struct Dungeon, max_gameplay_score, SV_U32),
    SAVE_FIELD(struct Dungeon, highest_task_number, SV_I16),
    SAVE_FIELD(struct Dungeon, total_money_owned, SV_I32),
    SAVE_FIELD(struct Dungeon, offmap_money_owned, SV_I32),
    SAVE_SUB_ARRAY(struct Dungeon, task_list, MapTask),
    SAVE_FIELD(struct Dungeon, task_count, SV_I32),
    SAVE_FIELD(struct Dungeon, owner, SV_U8),
    SAVE_FIELD_EX(struct Dungeon, camera_deviate_quake, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Dungeon, camera_deviate_jump, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD(struct Dungeon, score, SV_I32),
    SAVE_SUB_ARRAY(struct Dungeon, research, ResearchVal),
    SAVE_FIELD(struct Dungeon, current_research_idx, SV_I32),
    SAVE_FIELD(struct Dungeon, research_num, SV_U16),
    SAVE_ARRAY(struct Dungeon, creature_force_enabled, SV_U8),
    SAVE_ARRAY(struct Dungeon, creature_allowed, SV_U8),
    SAVE_ARRAY(struct Dungeon, magic_level, SV_U16),
    SAVE_ARRAY(struct Dungeon, magic_resrchable, SV_U16),
    SAVE_SUB_ARRAY(struct Dungeon, turn_timers, TurnTimer),
    SAVE_FIELD(struct Dungeon, max_creatures_attracted, SV_I32),
    SAVE_FIELD(struct Dungeon, heart_destroy_state, SV_U8),
    SAVE_FIELD(struct Dungeon, heart_destroy_turn, SV_I32),
    SAVE_SUB(struct Dungeon, essential_pos, Coord3d),
    SAVE_SUB_ARRAY(struct Dungeon, digger_stack, DiggerStack),
    SAVE_FIELD(struct Dungeon, digger_stack_update_turn, SV_U32),
    SAVE_FIELD(struct Dungeon, digger_stack_length, SV_U32),
    SAVE_ARRAY(struct Dungeon, visible_battles, SV_U8),
    SAVE_FIELD(struct Dungeon, zoom_annoyed_creature_idx, SV_I16),
    SAVE_FIELD(struct Dungeon, total_experience_creatures_gained, SV_I32),
    SAVE_FIELD(struct Dungeon, total_research_points, SV_I32),
    SAVE_FIELD(struct Dungeon, total_manufacture_points, SV_I32),
    SAVE_FIELD(struct Dungeon, manufacture_progress, SV_I32),
    SAVE_FIELD(struct Dungeon, manufacture_class, SV_U8),
    SAVE_FIELD_EX(struct Dungeon, manufacture_kind, SV_I16, .flags = 0, .name_domain = SND_ByManufactureClass),
    SAVE_FIELD(struct Dungeon, turn_last_manufacture, SV_I32),
    SAVE_FIELD(struct Dungeon, manufacture_level, SV_I32),
    SAVE_FIELD(struct Dungeon, research_progress, SV_I32),
    SAVE_SUB(struct Dungeon, lvstats, LevelStats),
    SAVE_SUB_ARRAY(struct Dungeon, dead_creatures, CreatureStorage),
    SAVE_FIELD(struct Dungeon, dead_creatures_count, SV_I32),
    SAVE_FIELD(struct Dungeon, dead_creature_idx, SV_I32),
    SAVE_ARRAY(struct Dungeon, event_button_index, SV_U8),
    SAVE_ARRAY(struct Dungeon, tortured_creatures, SV_U16),
    SAVE_FIELD(struct Dungeon, bodies_rotten_for_vampire, SV_U8),
    SAVE_FIELD(struct Dungeon, portal_scavenge_boost, SV_I32),
    SAVE_ARRAY(struct Dungeon, creature_models_joined, SV_U8),
    SAVE_FIELD(struct Dungeon, fights_num, SV_U32),
    SAVE_FIELD(struct Dungeon, research_override, SV_U8),
    SAVE_FIELD(struct Dungeon, last_creature_dropped_gameturn, SV_I32),
    SAVE_FIELD(struct Dungeon, devastation_centr_x, SV_I32),
    SAVE_FIELD(struct Dungeon, devastation_centr_y, SV_I32),
    SAVE_FIELD(struct Dungeon, devastation_turn, SV_U32),
    SAVE_FIELD(struct Dungeon, creatures_total_pay, SV_I32),
    SAVE_FIELD(struct Dungeon, gold_hoard_for_pickup, SV_U16),
    SAVE_FIELD(struct Dungeon, gold_pickup_amount, SV_U32),
    SAVE_ARRAY(struct Dungeon, selected_creatures_of_model, SV_U16),
    SAVE_ARRAY(struct Dungeon, selected_creatures_of_gui_job, SV_U16),
    SAVE_FIELD(struct Dungeon, texture_pack, SV_U8),
    SAVE_FIELD(struct Dungeon, color_idx, SV_U8),
    SAVE_SUB(struct Dungeon, modifier, Modifiers),
    SAVE_SUB(struct Dungeon, mnfct_info, TrapInfo),
    SAVE_SUB(struct Dungeon, box_info, BoxInfo),
    SAVE_SUB(struct Dungeon, trap_info, BoxInfo),
    SAVE_SUB(struct Dungeon, last_combat_location, Coord3d),
    SAVE_SUB(struct Dungeon, last_eventful_death_location, Coord3d),
    SAVE_SUB(struct Dungeon, last_trap_event_location, Coord3d),
    SAVE_ARRAY(struct Dungeon, creature_awarded, SV_I32),
    SAVE_FIELD(struct Dungeon, creature_entrance_level, SV_U8),
    SAVE_FIELD(struct Dungeon, evil_creatures_converted, SV_U32),
    SAVE_FIELD(struct Dungeon, good_creatures_converted, SV_U32),
    SAVE_FIELD(struct Dungeon, creatures_transferred, SV_U32),
    SAVE_FIELD(struct Dungeon, traps_sold, SV_U32),
    SAVE_FIELD(struct Dungeon, doors_sold, SV_U32),
    SAVE_FIELD(struct Dungeon, manufacture_gold, SV_U32),
    SAVE_FIELD(struct Dungeon, creatures_total_backpay, SV_I32),
    SAVE_FIELD(struct Dungeon, cheaper_diggers, SV_I32),
    SAVE_ARRAY(struct Dungeon, event_last_run_turn, SV_I32),
    SAVE_ARRAY(struct Dungeon, script_flags, SV_I32),
    SAVE_ARRAY(struct Dungeon, room_list_start, SV_U16),
    SAVE_ARRAY(struct Dungeon, room_buildable, SV_U8),
    SAVE_ARRAY(struct Dungeon, room_resrchable, SV_U8),
    SAVE_ARRAY(struct Dungeon, room_discrete_count, SV_U8),
    SAVE_FIELD(struct Dungeon, backup_heart_idx, SV_U16),
    SAVE_FIELD(struct Dungeon, free_soul_idx, SV_U16),
    SAVE_SUB_ARRAY2(struct Dungeon, hand_rules, HandRule),
);

SAVE_STRUCT(HandRule, struct HandRule,
    SAVE_FIELD(struct HandRule, type, SV_I8),
    SAVE_FIELD(struct HandRule, enabled, SV_I8),
    SAVE_FIELD(struct HandRule, allow, SV_I8),
    SAVE_FIELD(struct HandRule, param, SV_I32),
);

SAVE_STRUCT(LevelStats, struct LevelStats,
    SAVE_FIELD(struct LevelStats, things_researched, SV_U32),
    SAVE_FIELD(struct LevelStats, creatures_attracted, SV_U32),
    SAVE_FIELD(struct LevelStats, gold_mined, SV_U32),
    SAVE_FIELD(struct LevelStats, manufactured_doors, SV_U32),
    SAVE_FIELD(struct LevelStats, manufactured_traps, SV_U32),
    SAVE_FIELD(struct LevelStats, manufactured_items, SV_U32),
    SAVE_FIELD(struct LevelStats, start_time, SV_U32),
    SAVE_FIELD(struct LevelStats, end_time, SV_U32),
    SAVE_FIELD(struct LevelStats, creatures_trained, SV_U32),
    SAVE_FIELD(struct LevelStats, creatures_tortured, SV_U32),
    SAVE_FIELD(struct LevelStats, creatures_sacrificed, SV_U32),
    SAVE_FIELD(struct LevelStats, creatures_converted, SV_U32),
    SAVE_FIELD(struct LevelStats, creatures_summoned, SV_U32),
    SAVE_FIELD(struct LevelStats, num_slaps, SV_U32),
    SAVE_FIELD(struct LevelStats, num_caveins, SV_U32),
    SAVE_FIELD(struct LevelStats, bridges_built, SV_U32),
    SAVE_FIELD(struct LevelStats, rock_dug_out, SV_U32),
    SAVE_FIELD(struct LevelStats, salary_cost, SV_U32),
    SAVE_FIELD(struct LevelStats, flies_killed_by_spiders, SV_U32),
    SAVE_FIELD(struct LevelStats, territory_destroyed, SV_U32),
    SAVE_FIELD(struct LevelStats, territory_lost, SV_U32),
    SAVE_FIELD(struct LevelStats, rooms_constructed, SV_U32),
    SAVE_FIELD(struct LevelStats, traps_used, SV_U32),
    SAVE_FIELD(struct LevelStats, traps_armed, SV_U32),
    SAVE_FIELD(struct LevelStats, doors_used, SV_U32),
    SAVE_FIELD(struct LevelStats, keepers_destroyed, SV_U32),
    SAVE_FIELD(struct LevelStats, area_claimed, SV_U32),
    SAVE_FIELD(struct LevelStats, backs_stabbed, SV_U32),
    SAVE_FIELD(struct LevelStats, chickens_hatched, SV_U32),
    SAVE_FIELD(struct LevelStats, chickens_eaten, SV_U32),
    SAVE_FIELD(struct LevelStats, chickens_wasted, SV_U32),
    SAVE_FIELD(struct LevelStats, promises_broken, SV_U32),
    SAVE_FIELD(struct LevelStats, ghosts_raised, SV_U32),
    SAVE_FIELD(struct LevelStats, skeletons_raised, SV_U32),
    SAVE_FIELD(struct LevelStats, friendly_kills, SV_U32),
    SAVE_FIELD(struct LevelStats, lies_told, SV_U32),
    SAVE_FIELD(struct LevelStats, creatures_annoyed, SV_U32),
    SAVE_FIELD(struct LevelStats, graveyard_bodys, SV_U32),
    SAVE_FIELD(struct LevelStats, vamps_created, SV_U32),
    SAVE_FIELD(struct LevelStats, num_creatures, SV_U32),
    SAVE_FIELD(struct LevelStats, imps_deployed, SV_U32),
    SAVE_FIELD(struct LevelStats, battles_won, SV_U32),
    SAVE_FIELD(struct LevelStats, battles_lost, SV_U32),
    SAVE_FIELD(struct LevelStats, money, SV_U32),
    SAVE_FIELD(struct LevelStats, dngn_breached_count, SV_U32),
    SAVE_FIELD(struct LevelStats, doors_destroyed, SV_U32),
    SAVE_FIELD(struct LevelStats, rooms_destroyed, SV_U32),
    SAVE_FIELD(struct LevelStats, dungeon_area, SV_U32),
    SAVE_FIELD(struct LevelStats, ideas_researched, SV_U32),
    SAVE_FIELD(struct LevelStats, creatures_scavenged, SV_U32),
    SAVE_FIELD(struct LevelStats, creatures_from_sacrifice, SV_U32),
    SAVE_FIELD(struct LevelStats, spells_stolen, SV_U32),
    SAVE_FIELD(struct LevelStats, gold_pots_stolen, SV_U32),
    SAVE_FIELD(struct LevelStats, average_room_efficiency, SV_U32),
    SAVE_FIELD(struct LevelStats, player_rating, SV_U32),
    SAVE_FIELD(struct LevelStats, player_style, SV_U32),
    SAVE_FIELD(struct LevelStats, doors_unused, SV_U32),
    SAVE_FIELD(struct LevelStats, traps_unused, SV_U32),
    SAVE_FIELD(struct LevelStats, num_rooms, SV_U32),
    SAVE_FIELD(struct LevelStats, gameplay_time, SV_U32),
    SAVE_FIELD(struct LevelStats, num_entrances, SV_U32),
    SAVE_FIELD(struct LevelStats, hopes_dashed, SV_U32),
    SAVE_FIELD(struct LevelStats, allow_save_score, SV_U32),
    SAVE_FIELD(struct LevelStats, player_score, SV_U32),
    SAVE_ARRAY(struct LevelStats, keeper_destroyed, SV_U32),
);

SAVE_STRUCT(Modifiers, struct Modifiers,
    SAVE_FIELD(struct Modifiers, health, SV_U16),
    SAVE_FIELD(struct Modifiers, strength, SV_U16),
    SAVE_FIELD(struct Modifiers, armour, SV_U16),
    SAVE_FIELD(struct Modifiers, spell_damage, SV_U16),
    SAVE_FIELD(struct Modifiers, speed, SV_U16),
    SAVE_FIELD(struct Modifiers, pay, SV_U16),
    SAVE_FIELD(struct Modifiers, training_cost, SV_U16),
    SAVE_FIELD(struct Modifiers, scavenging_cost, SV_U16),
    SAVE_FIELD(struct Modifiers, loyalty, SV_U16),
);

SAVE_STRUCT(OpponentRelation, struct OpponentRelation,
    SAVE_FIELD(struct OpponentRelation, last_interaction_turn, SV_U32),
    SAVE_FIELD(struct OpponentRelation, next_idx, SV_I16),
    SAVE_FIELD(struct OpponentRelation, hate_amount, SV_I32),
    SAVE_SUB_ARRAY(struct OpponentRelation, pos_A, Coord3d),
);

SAVE_STRUCT(PerExpLevelValues, struct PerExpLevelValues,
    SAVE_ARRAY(struct PerExpLevelValues, value, SV_U8),
);

SAVE_STRUCT(PlayerInfo, struct PlayerInfo,
    SAVE_FIELD(struct PlayerInfo, allocflags, SV_U8),
    SAVE_FIELD(struct PlayerInfo, display_flags, SV_U8),
    SAVE_FIELD_EX(struct PlayerInfo, user_id, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD(struct PlayerInfo, hand_animationId, SV_I32),
    SAVE_FIELD(struct PlayerInfo, hand_busy_until_turn, SV_U32),
    SAVE_STRING(struct PlayerInfo, player_name),  /* plain-char */
    SAVE_FIELD(struct PlayerInfo, victory_state, SV_U8),
    SAVE_FIELD(struct PlayerInfo, allied_players, SV_U16),
    SAVE_FIELD(struct PlayerInfo, players_with_locked_ally_status, SV_U16),
    SAVE_FIELD(struct PlayerInfo, id_number, SV_U8),
    SAVE_FIELD_EX(struct PlayerInfo, unused, SV_BOOL8, .aliases = (const char *const[]){ "is_active", NULL }),
    SAVE_FIELD(struct PlayerInfo, controlled_thing_idx, SV_I16),
    SAVE_FIELD(struct PlayerInfo, controlled_thing_creatrn, SV_U32),
    SAVE_FIELD_EX(struct PlayerInfo, thing_under_hand, SV_I16, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, possession_lock, SV_BOOL8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, zoom_to_pos_x, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, zoom_to_pos_y, SV_I32, .flags = SVF_SAVE),
    SAVE_SUB(struct PlayerInfo, wandr_within, Wander),
    SAVE_SUB(struct PlayerInfo, wandr_outside, Wander),
    SAVE_FIELD(struct PlayerInfo, hand_thing_idx, SV_I16),
    SAVE_FIELD(struct PlayerInfo, cta_flag_idx, SV_I16),
    SAVE_FIELD(struct PlayerInfo, influenced_thing_idx, SV_I16),
    SAVE_FIELD(struct PlayerInfo, influenced_thing_creation, SV_U32),
    SAVE_FIELD(struct PlayerInfo, work_state, SV_U8),
    SAVE_FIELD(struct PlayerInfo, continue_work_state, SV_U8),
    SAVE_ARRAY_EX(struct PlayerInfo, mp_message_text, SV_STR, .flags = SVF_SAVE),  /* plain-char */
    SAVE_ARRAY_EX(struct PlayerInfo, mp_pending_message, SV_STR, .flags = SVF_SAVE),  /* plain-char */
    SAVE_ARRAY_EX(struct PlayerInfo, mp_message_text_last, SV_STR, .flags = SVF_SAVE),  /* plain-char */
    SAVE_FIELD(struct PlayerInfo, instance_num, SV_U8),
    SAVE_FIELD(struct PlayerInfo, instance_remain_turns, SV_U32),
    SAVE_FIELD(struct PlayerInfo, cast_expand_level, SV_I32),
    SAVE_FIELD(struct PlayerInfo, power_of_cooldown_turn, SV_U32),
    SAVE_FIELD(struct PlayerInfo, game_version, SV_I32),
    SAVE_FIELD_EX(struct PlayerInfo, display_objective_turn, SV_U32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, hand_idx, SV_U8, .flags = SVF_SAVE),
    SAVE_SUB_EX(struct PlayerInfo, render_roomspace, RoomSpace, .flags = SVF_SAVE),
    SAVE_SUB_EX(struct PlayerInfo, roomspace, RoomSpace, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, roomspace_mode, SV_U8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, roomspace_detection_looseness, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, roomspace_width, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, roomspace_height, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, roomspace_highlight_mode, SV_U8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, roomspace_drag_paint_mode, SV_BOOL8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, roomspace_l_shape, SV_U8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct PlayerInfo, roomspace_horizontal_first, SV_BOOL8, .flags = SVF_SAVE),
    SAVE_FIELD(struct PlayerInfo, player_type, SV_U8),
    SAVE_FIELD(struct PlayerInfo, special_digger, SV_I16),
    SAVE_FIELD(struct PlayerInfo, generate_speed, SV_U16),
);

SAVE_STRUCT(ResearchVal, struct ResearchVal,
    SAVE_FIELD(struct ResearchVal, rtyp, SV_U8),
    SAVE_FIELD(struct ResearchVal, rkind, SV_U16),
    SAVE_FIELD(struct ResearchVal, req_amount, SV_I32),
);

SAVE_STRUCT(RoomSpace, struct RoomSpace,
    SAVE_ARRAY2(struct RoomSpace, slab_grid, SV_BOOL8),
    SAVE_FIELD(struct RoomSpace, slab_count, SV_I32),
    SAVE_FIELD(struct RoomSpace, is_roomspace_a_box, SV_BOOL8),
    SAVE_FIELD(struct RoomSpace, width, SV_I32),
    SAVE_FIELD(struct RoomSpace, height, SV_I32),
    SAVE_FIELD(struct RoomSpace, left, SV_I16),
    SAVE_FIELD(struct RoomSpace, top, SV_I16),
    SAVE_FIELD(struct RoomSpace, right, SV_I16),
    SAVE_FIELD(struct RoomSpace, bottom, SV_I16),
    SAVE_FIELD(struct RoomSpace, centreX, SV_I16),
    SAVE_FIELD(struct RoomSpace, centreY, SV_I16),
    SAVE_FIELD(struct RoomSpace, total_roomspace_cost, SV_I32),
    SAVE_FIELD(struct RoomSpace, invalid_slabs_count, SV_I32),
    SAVE_FIELD(struct RoomSpace, user, SV_I32),
    SAVE_FIELD(struct RoomSpace, plyr_idx, SV_I8),
    SAVE_FIELD(struct RoomSpace, rkind, SV_U8),
    SAVE_FIELD(struct RoomSpace, is_roomspace_a_single_subtile, SV_BOOL8),
    SAVE_FIELD(struct RoomSpace, buildx, SV_I16),
    SAVE_FIELD(struct RoomSpace, buildy, SV_I16),
    SAVE_FIELD(struct RoomSpace, is_active, SV_BOOL8),
    SAVE_FIELD(struct RoomSpace, render_roomspace_as_box, SV_BOOL8),
    SAVE_FIELD(struct RoomSpace, tag_for_dig, SV_BOOL8),
    SAVE_FIELD(struct RoomSpace, highlight_mode, SV_BOOL8),
    SAVE_FIELD(struct RoomSpace, untag_mode, SV_BOOL8),
    SAVE_FIELD(struct RoomSpace, one_click_mode_exclusive, SV_BOOL8),
    SAVE_FIELD(struct RoomSpace, drag_start_x, SV_I16),
    SAVE_FIELD(struct RoomSpace, drag_start_y, SV_I16),
    SAVE_FIELD(struct RoomSpace, drag_end_x, SV_I16),
    SAVE_FIELD(struct RoomSpace, drag_end_y, SV_I16),
    SAVE_FIELD(struct RoomSpace, drag_mode, SV_BOOL8),
    SAVE_FIELD(struct RoomSpace, drag_direction, SV_U8),
);

SAVE_STRUCT(SubtileXY, struct SubtileXY,
    SAVE_FIELD(struct SubtileXY, stl_x, SV_I32),
    SAVE_FIELD(struct SubtileXY, stl_y, SV_I32),
);

SAVE_STRUCT(TrapInfo, struct TrapInfo,
    SAVE_ARRAY(struct TrapInfo, trap_amount_offmap, SV_U8),
    SAVE_ARRAY(struct TrapInfo, trap_amount_stored, SV_U8),
    SAVE_ARRAY(struct TrapInfo, trap_build_flags, SV_U8),
    SAVE_ARRAY(struct TrapInfo, trap_amount_placeable, SV_U8),
    SAVE_ARRAY(struct TrapInfo, door_amount_offmap, SV_U8),
    SAVE_ARRAY(struct TrapInfo, door_amount_stored, SV_U8),
    SAVE_ARRAY(struct TrapInfo, door_build_flags, SV_U8),
    SAVE_ARRAY(struct TrapInfo, door_amount_placeable, SV_U8),
);

SAVE_STRUCT(TurnTimer, struct TurnTimer,
    SAVE_FIELD(struct TurnTimer, count, SV_U32),
    SAVE_FIELD(struct TurnTimer, state, SV_U8),
);

SAVE_STRUCT(DungeonCamera, struct DungeonCamera,
    SAVE_FIELD(struct DungeonCamera, x, SV_I32),
    SAVE_FIELD(struct DungeonCamera, y, SV_I32),
    SAVE_ARRAY(struct DungeonCamera, zoom, SV_I32),
    SAVE_ARRAY(struct DungeonCamera, yaw, SV_I32),
    SAVE_FIELD(struct DungeonCamera, pitch, SV_I32),
);

SAVE_STRUCT(UserState, struct UserState,
    SAVE_FIELD(struct UserState, init_flags, SV_U8),
    SAVE_FIELD(struct UserState, additional_flags, SV_U8),
    SAVE_FIELD(struct UserState, input_crtr_control, SV_U8),
    SAVE_FIELD(struct UserState, input_crtr_query, SV_U8),
    SAVE_FIELD(struct UserState, cursor_light_idx, SV_I16),
    SAVE_FIELD(struct UserState, cursor_subtile_x, SV_I32),
    SAVE_FIELD(struct UserState, cursor_subtile_y, SV_I32),
    SAVE_FIELD(struct UserState, previous_cursor_subtile_x, SV_I32),
    SAVE_FIELD(struct UserState, previous_cursor_subtile_y, SV_I32),
    SAVE_FIELD(struct UserState, cursor_clicked_subtile_x, SV_I32),
    SAVE_FIELD(struct UserState, cursor_clicked_subtile_y, SV_I32),
    SAVE_FIELD(struct UserState, cursor_button_down, SV_U8),
    SAVE_FIELD(struct UserState, mouse_on_map, SV_BOOL8),
    SAVE_FIELD(struct UserState, primary_cursor_state, SV_U8),
    SAVE_FIELD(struct UserState, secondary_cursor_state, SV_U8),
    SAVE_FIELD(struct UserState, one_click_mode_exclusive, SV_BOOL8),
    SAVE_FIELD(struct UserState, one_click_lock_cursor, SV_BOOL8),
    SAVE_FIELD(struct UserState, ignore_next_PCtr_RBtnRelease, SV_BOOL8),
    SAVE_FIELD(struct UserState, ignore_next_PCtr_LBtnRelease, SV_BOOL8),
    SAVE_FIELD(struct UserState, swap_to_untag_mode, SV_I8),
    SAVE_FIELD(struct UserState, interpolated_tagging, SV_BOOL8),
    SAVE_FIELD(struct UserState, first_person_dig_claim_mode, SV_BOOL8),
    SAVE_FIELD_EX(struct UserState, view_type, SV_U8, .flags = SVF_SAVE),
    SAVE_SUB_EX(struct UserState, dungeon_camera, DungeonCamera, .flags = SVF_SAVE),
    SAVE_RUNTIME(struct UserState, prefs),
    SAVE_FIELD(struct UserState, selected_fp_thing_pickup, SV_U16),
    SAVE_FIELD(struct UserState, teleport_destination, SV_U8),
    SAVE_FIELD(struct UserState, nearest_teleport, SV_BOOL8),
    SAVE_FIELD(struct UserState, battleid, SV_U8),
    SAVE_SUB(struct UserState, cheatselection, CheatSelection),
    SAVE_FIELD(struct UserState, boxsize, SV_U8),
    SAVE_FIELD(struct UserState, chosen_room_kind, SV_U8),
    SAVE_FIELD(struct UserState, full_slab_cursor, SV_U8),
    SAVE_FIELD(struct UserState, chosen_trap_kind, SV_I16),
    SAVE_FIELD(struct UserState, chosen_door_kind, SV_I16),
    SAVE_FIELD_EX(struct UserState, chosen_power_kind, SV_U16, .flags = 0, .name_domain = SND_Power),
    SAVE_FIELD(struct UserState, pickup_all_gold, SV_BOOL8),
);

SAVE_STRUCT(Wander, struct Wander,
    SAVE_FIELD(struct Wander, points_count, SV_U32),
    SAVE_FIELD(struct Wander, point_insert_idx, SV_U32),
    SAVE_FIELD(struct Wander, last_checked_slb_num, SV_U32),
    SAVE_FIELD(struct Wander, num_check_per_run, SV_U32),
    SAVE_FIELD(struct Wander, max_found_per_check, SV_U32),
    SAVE_FIELD(struct Wander, search_limiting_enabled, SV_U8),
    SAVE_FIELD(struct Wander, wandr_slot, SV_U8),
    SAVE_FIELD(struct Wander, plyr_idx, SV_I8),
    SAVE_FIELD(struct Wander, plyr_bit, SV_U16),
    SAVE_SUB_ARRAY(struct Wander, points, SubtileXY),
);
