/** @file schema_config.c
 *     Field tables for saved structs.
 */
#include "pre_inc.h"
#include "kfx/save/SaveTypes.h"
#include "game_legacy.h"
#include "game_merge.h"
#include "packets.h"
#include "config_campaigns.h"
#include "front_network.h"
#include "post_inc.h"
#include "kfx/save/core/save_schema.h"
#include "kfx/save/core/schema/save_tables_decl.h"

SAVE_STRUCT(ColumnConfig, struct ColumnConfig,
    SAVE_FIELD(struct ColumnConfig, columns_count, SV_I32),
    SAVE_SUB_ARRAY(struct ColumnConfig, cols, Column),
);

SAVE_STRUCT(CommandWord, struct CommandWord,
    SAVE_STRING(struct CommandWord, text),  /* plain-char */
);

SAVE_STRUCT(ComponentVector, struct ComponentVector,
    SAVE_FIELD(struct ComponentVector, x, SV_I16),
    SAVE_FIELD(struct ComponentVector, y, SV_I16),
    SAVE_FIELD(struct ComponentVector, z, SV_I16),
);

SAVE_STRUCT(ComputerRulesConfig, struct ComputerRulesConfig,
    SAVE_FIELD(struct ComputerRulesConfig, disease_to_temple_pct, SV_U16),
);

SAVE_STRUCT(Configs, struct Configs,
    SAVE_SUB(struct Configs, slab_conf, SlabsConfig),
    SAVE_SUB(struct Configs, power_hand_conf, PowerHandConfig),
    SAVE_SUB(struct Configs, magic_conf, MagicConfig),
    SAVE_SUB(struct Configs, cube_conf, CubesConfig),
    SAVE_SUB(struct Configs, trapdoor_conf, TrapDoorConfig),
    SAVE_SUB(struct Configs, effects_conf, EffectsConfig),
    SAVE_SUB(struct Configs, crtr_conf, CreatureConfig),
    SAVE_SUB(struct Configs, object_conf, ObjectsConfig),
    SAVE_SUB_ARRAY(struct Configs, rules, RulesConfig),
    SAVE_SUB(struct Configs, plyr_conf, PlayerStateConfig),
    SAVE_SUB(struct Configs, column_conf, ColumnConfig),
    SAVE_SUB(struct Configs, lua, LuaFuncsConf),
);

SAVE_STRUCT(CreatureAngerJobConfig, struct CreatureAngerJobConfig,
    SAVE_STRING(struct CreatureAngerJobConfig, name),  /* plain-char */
);

SAVE_STRUCT(CreatureConfig, struct CreatureConfig,
    SAVE_FIELD(struct CreatureConfig, model_count, SV_I32),
    SAVE_SUB_ARRAY(struct CreatureConfig, model, CreatureModelConfig),
    SAVE_FIELD(struct CreatureConfig, states_count, SV_I32),
    SAVE_SUB_ARRAY(struct CreatureConfig, states, CreatureStateConfig),
    SAVE_FIELD(struct CreatureConfig, instances_count, SV_I32),
    SAVE_SUB_ARRAY(struct CreatureConfig, instances, CreatureInstanceConfig),
    SAVE_FIELD(struct CreatureConfig, jobs_count, SV_I32),
    SAVE_SUB_ARRAY(struct CreatureConfig, jobs, CreatureJobConfig),
    SAVE_FIELD(struct CreatureConfig, angerjobs_count, SV_I32),
    SAVE_SUB_ARRAY(struct CreatureConfig, angerjobs, CreatureAngerJobConfig),
    SAVE_FIELD(struct CreatureConfig, attacktypes_count, SV_I32),
    SAVE_SUB_ARRAY(struct CreatureConfig, attacktypes, CommandWord),
    SAVE_SUB(struct CreatureConfig, exp, CreatureExperience),
    SAVE_FIELD(struct CreatureConfig, special_digger_good, SV_I16),
    SAVE_FIELD(struct CreatureConfig, special_digger_evil, SV_I16),
    SAVE_FIELD(struct CreatureConfig, spectator_breed, SV_I16),
    SAVE_ARRAY2(struct CreatureConfig, creature_graphics, SV_I16),
    SAVE_FIELD(struct CreatureConfig, sprite_size, SV_I32),
    SAVE_SUB_ARRAY(struct CreatureConfig, creature_sounds, CreatureSounds),
);

SAVE_STRUCT(CreatureExperience, struct CreatureExperience,
    SAVE_FIELD(struct CreatureExperience, size_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, pay_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, spell_damage_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, range_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, job_value_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, health_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, strength_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, dexterity_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, defense_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, loyalty_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, armour_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, exp_on_hitting_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, training_cost_increase_on_exp, SV_I32),
    SAVE_FIELD(struct CreatureExperience, scavenging_cost_increase_on_exp, SV_I32),
);

SAVE_STRUCT(CreatureInstanceConfig, struct CreatureInstanceConfig,
    SAVE_STRING(struct CreatureInstanceConfig, name),  /* plain-char */
);

SAVE_STRUCT(CreatureJobConfig, struct CreatureJobConfig,
    SAVE_STRING(struct CreatureJobConfig, name),  /* plain-char */
    SAVE_FIELD(struct CreatureJobConfig, func_plyr_check_idx, SV_U8),
    SAVE_FIELD(struct CreatureJobConfig, func_plyr_assign_idx, SV_U8),
    SAVE_FIELD(struct CreatureJobConfig, func_cord_check_idx, SV_U8),
    SAVE_FIELD(struct CreatureJobConfig, func_cord_assign_idx, SV_U8),
    SAVE_FIELD(struct CreatureJobConfig, room_role, SV_U32),
    SAVE_FIELD(struct CreatureJobConfig, event_kind, SV_U8),
    SAVE_FIELD(struct CreatureJobConfig, initial_crstate, SV_U16),
    SAVE_FIELD(struct CreatureJobConfig, continue_crstate, SV_U16),
    SAVE_FIELD(struct CreatureJobConfig, job_flags, SV_U32),
);

SAVE_STRUCT(CreatureModelConfig, struct CreatureModelConfig,
    SAVE_STRING(struct CreatureModelConfig, name),  /* plain-char */
    SAVE_FIELD(struct CreatureModelConfig, namestr_idx, SV_I32),
    SAVE_FIELD(struct CreatureModelConfig, model_flags, SV_U32),
    SAVE_FIELD(struct CreatureModelConfig, job_primary, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, job_secondary, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, jobs_not_do, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, eye_effect, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, health, SV_I32),
    SAVE_FIELD(struct CreatureModelConfig, heal_requirement, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, heal_threshold, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, fall_acceleration, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, inertia_floor, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, inertia_air, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, strength, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, armour, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, dexterity, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, fear_wounded, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, defense, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, luck, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, sleep_recovery, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, hunger_rate, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, hunger_fill, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, annoy_level, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, lair_size, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, hurt_by_lava, SV_U8),
    SAVE_ARRAY(struct CreatureModelConfig, sleep_exp_slab, SV_U8),
    SAVE_ARRAY(struct CreatureModelConfig, sleep_experience, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, exp_for_hitting, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, gold_hold, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, training_cost, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, scavenger_cost, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, scavenge_require, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, scavenge_value, SV_U8),
    SAVE_ARRAY(struct CreatureModelConfig, to_level, SV_U32),
    SAVE_FIELD(struct CreatureModelConfig, base_speed, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, grow_up, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, grow_up_level, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, entrance_force, SV_BOOL8),
    SAVE_FIELD(struct CreatureModelConfig, max_turning_speed, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, base_eye_height, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, size_xy, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, size_z, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, thing_size_xy, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, thing_size_z, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, shot_shift_x, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, shot_shift_y, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, shot_shift_z, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, walking_anim_speed, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, flying, SV_BOOL8),
    SAVE_FIELD(struct CreatureModelConfig, fixed_anim_speed, SV_BOOL8),
    SAVE_FIELD(struct CreatureModelConfig, attack_preference, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, field_of_view, SV_I16),
    SAVE_ARRAY(struct CreatureModelConfig, learned_instance_id, SV_I16),
    SAVE_ARRAY(struct CreatureModelConfig, learned_instance_level, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, research_value, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, humanoid_creature, SV_BOOL8),
    SAVE_FIELD(struct CreatureModelConfig, piss_on_dead, SV_BOOL8),
    SAVE_FIELD(struct CreatureModelConfig, training_value, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, pay, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, manufacture_value, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, hearing, SV_U8),
    SAVE_ARRAY(struct CreatureModelConfig, entrance_rooms, SV_U8),
    SAVE_ARRAY(struct CreatureModelConfig, entrance_slabs_req, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, visual_range, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, partner_training, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, torture_break_time, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_no_lair, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_no_hatchery, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_woken_up, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_on_dead_friend, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_sulking, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_no_salary, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_slapped, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_on_dead_enemy, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_in_temple, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_sleeping, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_got_wage, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_in_torture, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_win_battle, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_untrained_time, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_untrained, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_queue, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_will_not_do_job, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, job_stress, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_job_stress, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, jobs_anger, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_others_leaving, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, slaps_to_kill, SV_U8),
    SAVE_ARRAY(struct CreatureModelConfig, lair_enemy, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, rebirth, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, can_see_invisible, SV_BOOL8),
    SAVE_FIELD(struct CreatureModelConfig, can_go_locked_doors, SV_BOOL8),
    SAVE_FIELD(struct CreatureModelConfig, bleeds, SV_BOOL8),
    SAVE_FIELD(struct CreatureModelConfig, annoy_eat_food, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_in_hand, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, damage_to_boulder, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, fear_stronger, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, fearsome_factor, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, entrance_score, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, annoy_going_postal, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, toking_recovery, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, illuminated, SV_BOOL8),
    SAVE_FIELD(struct CreatureModelConfig, transparency_flags, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, corpse_vanish_effect, SV_I8),
    SAVE_FIELD(struct CreatureModelConfig, footstep_pitch, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, lair_object, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, status_offset, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, evil_start_state, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, good_start_state, SV_U16),
    SAVE_FIELD(struct CreatureModelConfig, natural_death_kind, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, swipe_idx, SV_U8),
    SAVE_FIELD(struct CreatureModelConfig, prison_kind, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, torture_kind, SV_I16),
    SAVE_ARRAY(struct CreatureModelConfig, hostile_towards, SV_I16),
    SAVE_FIELD(struct CreatureModelConfig, immunity_flags, SV_U32),
    SAVE_SUB(struct CreatureModelConfig, creature_picked_up_offset, PickedUpOffset),
);

SAVE_STRUCT(CreatureRulesConfig, struct CreatureRulesConfig,
    SAVE_FIELD(struct CreatureRulesConfig, recovery_frequency, SV_U8),
    SAVE_FIELD(struct CreatureRulesConfig, body_remains_for, SV_U16),
    SAVE_FIELD(struct CreatureRulesConfig, flee_zone_radius, SV_U32),
    SAVE_FIELD(struct CreatureRulesConfig, game_turns_in_flee, SV_I32),
    SAVE_FIELD(struct CreatureRulesConfig, game_turns_unconscious, SV_U16),
    SAVE_FIELD(struct CreatureRulesConfig, critical_health_permil, SV_I32),
    SAVE_FIELD(struct CreatureRulesConfig, stun_enemy_chance_evil, SV_U8),
    SAVE_FIELD(struct CreatureRulesConfig, stun_enemy_chance_good, SV_U8),
    SAVE_FIELD(struct CreatureRulesConfig, stun_without_prison_chance, SV_U8),
    SAVE_FIELD(struct CreatureRulesConfig, instance_delay_on_drop, SV_I32),
);

SAVE_STRUCT(CreatureSound, struct CreatureSound,
    SAVE_FIELD(struct CreatureSound, index, SV_I32),
    SAVE_FIELD(struct CreatureSound, count, SV_I16),
);

SAVE_STRUCT(CreatureSounds, struct CreatureSounds,
    SAVE_SUB(struct CreatureSounds, foot, CreatureSound),
    SAVE_SUB(struct CreatureSounds, hit, CreatureSound),
    SAVE_SUB(struct CreatureSounds, happy, CreatureSound),
    SAVE_SUB(struct CreatureSounds, sad, CreatureSound),
    SAVE_SUB(struct CreatureSounds, die, CreatureSound),
    SAVE_SUB(struct CreatureSounds, hang, CreatureSound),
    SAVE_SUB(struct CreatureSounds, drop, CreatureSound),
    SAVE_SUB(struct CreatureSounds, torture, CreatureSound),
    SAVE_SUB(struct CreatureSounds, slap, CreatureSound),
    SAVE_SUB(struct CreatureSounds, fight, CreatureSound),
    SAVE_SUB(struct CreatureSounds, piss, CreatureSound),
);

SAVE_STRUCT(CreatureStateConfig, struct CreatureStateConfig,
    SAVE_STRING(struct CreatureStateConfig, name),  /* plain-char */
    SAVE_FIELD(struct CreatureStateConfig, process_state, SV_I16),
    SAVE_FIELD(struct CreatureStateConfig, cleanup_state, SV_I16),
    SAVE_FIELD(struct CreatureStateConfig, move_from_slab, SV_I16),
    SAVE_FIELD(struct CreatureStateConfig, move_check, SV_I16),
    SAVE_FIELD(struct CreatureStateConfig, override_feed, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_own_needs, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_sleep, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_fight_crtr, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_gets_salary, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_captive, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_transition, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_escape, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_unconscious, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_anger_job, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_fight_object, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_fight_door, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_call2arms, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_follow, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, override_deep_work, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, state_type, SV_U8),
    SAVE_FIELD(struct CreatureStateConfig, captive, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, transition, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, follow_behavior, SV_U16),
    SAVE_FIELD(struct CreatureStateConfig, blocks_all_state_changes, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, sprite_idx, SV_U16),
    SAVE_FIELD(struct CreatureStateConfig, display_thought_bubble, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, sneaky, SV_BOOL8),
    SAVE_FIELD(struct CreatureStateConfig, react_to_cta, SV_BOOL8),
);

SAVE_STRUCT(CubeConfigStats, struct CubeConfigStats,
    SAVE_STRING(struct CubeConfigStats, code_name),  /* plain-char */
    SAVE_ARRAY(struct CubeConfigStats, texture_id, SV_U16),
    SAVE_FIELD(struct CubeConfigStats, ownershipGroup, SV_U8),
    SAVE_FIELD(struct CubeConfigStats, owner, SV_I8),
    SAVE_FIELD(struct CubeConfigStats, properties_flags, SV_U8),
);

SAVE_STRUCT(CubesConfig, struct CubesConfig,
    SAVE_FIELD(struct CubesConfig, cube_types_count, SV_I32),
    SAVE_SUB_ARRAY(struct CubesConfig, cube_cfgstats, CubeConfigStats),
    SAVE_ARRAY2(struct CubesConfig, cube_bits, SV_U16),
);

SAVE_STRUCT(DoorConfigStats, struct DoorConfigStats,
    SAVE_STRING(struct DoorConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct DoorConfigStats, name_stridx, SV_I32),
    SAVE_FIELD(struct DoorConfigStats, tooltip_stridx, SV_I32),
    SAVE_FIELD(struct DoorConfigStats, bigsym_sprite_idx, SV_I32),
    SAVE_FIELD(struct DoorConfigStats, medsym_sprite_idx, SV_I32),
    SAVE_FIELD(struct DoorConfigStats, pointer_sprite_idx, SV_I32),
    SAVE_FIELD(struct DoorConfigStats, panel_tab_idx, SV_I32),
    SAVE_FIELD(struct DoorConfigStats, manufct_level, SV_U8),
    SAVE_FIELD(struct DoorConfigStats, manufct_required, SV_U32),
    SAVE_FIELD(struct DoorConfigStats, health, SV_I32),
    SAVE_ARRAY(struct DoorConfigStats, slbkind, SV_U16),
    SAVE_FIELD(struct DoorConfigStats, open_speed, SV_U16),
    SAVE_FIELD(struct DoorConfigStats, model_flags, SV_U16),
    SAVE_FIELD(struct DoorConfigStats, selling_value, SV_I32),
    SAVE_FIELD(struct DoorConfigStats, unsellable, SV_BOOL8),
    SAVE_FIELD(struct DoorConfigStats, place_sound_idx, SV_I16),
    SAVE_FIELD(struct DoorConfigStats, updatefn_idx, SV_I16),
);

SAVE_STRUCT(EffectConfigStats, struct EffectConfigStats,
    SAVE_STRING(struct EffectConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct EffectConfigStats, start_health, SV_I32),
    SAVE_FIELD(struct EffectConfigStats, generation_type, SV_U8),
    SAVE_FIELD(struct EffectConfigStats, accel_xy_min, SV_I16),
    SAVE_FIELD(struct EffectConfigStats, accel_xy_max, SV_I16),
    SAVE_FIELD(struct EffectConfigStats, accel_z_min, SV_I16),
    SAVE_FIELD(struct EffectConfigStats, accel_z_max, SV_I16),
    SAVE_FIELD(struct EffectConfigStats, elements_count, SV_U8),
    SAVE_FIELD(struct EffectConfigStats, effect_sound, SV_I16),
    SAVE_FIELD(struct EffectConfigStats, kind_min, SV_I16),
    SAVE_FIELD(struct EffectConfigStats, kind_max, SV_I16),
    SAVE_FIELD(struct EffectConfigStats, area_affect_type, SV_U8),
    SAVE_FIELD(struct EffectConfigStats, always_generate, SV_U8),
    SAVE_SUB(struct EffectConfigStats, ilght, InitLight),
    SAVE_FIELD(struct EffectConfigStats, affected_by_wind, SV_U8),
    SAVE_FIELD(struct EffectConfigStats, effect_hit_type, SV_U8),
    SAVE_FIELD(struct EffectConfigStats, spell_effect, SV_U16),
);

SAVE_STRUCT(EffectElementConfigStats, struct EffectElementConfigStats,
    SAVE_STRING(struct EffectElementConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct EffectElementConfigStats, draw_class, SV_U8),
    SAVE_FIELD(struct EffectElementConfigStats, move_type, SV_U8),
    SAVE_FIELD(struct EffectElementConfigStats, unanimated, SV_U8),
    SAVE_FIELD(struct EffectElementConfigStats, lifespan, SV_I16),
    SAVE_FIELD(struct EffectElementConfigStats, lifespan_random, SV_I16),
    SAVE_FIELD(struct EffectElementConfigStats, sprite_idx, SV_I16),
    SAVE_FIELD(struct EffectElementConfigStats, sprite_size_min, SV_I16),
    SAVE_FIELD(struct EffectElementConfigStats, sprite_size_max, SV_I16),
    SAVE_FIELD(struct EffectElementConfigStats, animate_once, SV_U8),
    SAVE_FIELD(struct EffectElementConfigStats, sprite_speed_min, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, sprite_speed_max, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, animate_on_floor, SV_BOOL8),
    SAVE_FIELD(struct EffectElementConfigStats, unshaded, SV_BOOL8),
    SAVE_FIELD(struct EffectElementConfigStats, transparent, SV_U8),
    SAVE_FIELD(struct EffectElementConfigStats, movable, SV_BOOL8),
    SAVE_FIELD(struct EffectElementConfigStats, through_walls, SV_U8),
    SAVE_FIELD(struct EffectElementConfigStats, size_change, SV_U8),
    SAVE_FIELD(struct EffectElementConfigStats, fall_acceleration, SV_I8),
    SAVE_FIELD(struct EffectElementConfigStats, inertia_floor, SV_I16),
    SAVE_FIELD(struct EffectElementConfigStats, inertia_air, SV_I16),
    SAVE_FIELD(struct EffectElementConfigStats, subeffect_model, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, subeffect_delay, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, impacts, SV_BOOL8),
    SAVE_FIELD(struct EffectElementConfigStats, solidgnd_effmodel, SV_I16),
    SAVE_FIELD(struct EffectElementConfigStats, solidgnd_snd_smpid, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, solidgnd_loudness, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, solidgnd_destroy_on_impact, SV_BOOL8),
    SAVE_FIELD(struct EffectElementConfigStats, water_effmodel, SV_I16),
    SAVE_FIELD(struct EffectElementConfigStats, water_snd_smpid, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, water_loudness, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, water_destroy_on_impact, SV_BOOL8),
    SAVE_FIELD(struct EffectElementConfigStats, lava_effmodel, SV_I16),
    SAVE_FIELD(struct EffectElementConfigStats, lava_snd_smpid, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, lava_loudness, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, lava_destroy_on_impact, SV_BOOL8),
    SAVE_FIELD(struct EffectElementConfigStats, transform_model, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, light_radius, SV_U16),
    SAVE_FIELD(struct EffectElementConfigStats, light_intensity, SV_U8),
    SAVE_FIELD(struct EffectElementConfigStats, light_flags, SV_I32),
    SAVE_FIELD(struct EffectElementConfigStats, affected_by_wind, SV_U8),
);

SAVE_STRUCT(EffectGeneratorConfigStats, struct EffectGeneratorConfigStats,
    SAVE_STRING(struct EffectGeneratorConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct EffectGeneratorConfigStats, generation_delay_min, SV_I32),
    SAVE_FIELD(struct EffectGeneratorConfigStats, generation_delay_max, SV_I32),
    SAVE_FIELD(struct EffectGeneratorConfigStats, generation_amount, SV_I32),
    SAVE_FIELD(struct EffectGeneratorConfigStats, effect_model, SV_I16),
    SAVE_FIELD(struct EffectGeneratorConfigStats, ignore_terrain, SV_U8),
    SAVE_FIELD(struct EffectGeneratorConfigStats, spawn_height, SV_I32),
    SAVE_FIELD(struct EffectGeneratorConfigStats, acc_x_min, SV_I32),
    SAVE_FIELD(struct EffectGeneratorConfigStats, acc_x_max, SV_I32),
    SAVE_FIELD(struct EffectGeneratorConfigStats, acc_y_min, SV_I32),
    SAVE_FIELD(struct EffectGeneratorConfigStats, acc_y_max, SV_I32),
    SAVE_FIELD(struct EffectGeneratorConfigStats, acc_z_min, SV_I32),
    SAVE_FIELD(struct EffectGeneratorConfigStats, acc_z_max, SV_I32),
    SAVE_FIELD(struct EffectGeneratorConfigStats, sound_sample_idx, SV_I32),
    SAVE_FIELD(struct EffectGeneratorConfigStats, sound_sample_rng, SV_I32),
);

SAVE_STRUCT(Effects, struct Effects,
    SAVE_FIELD(struct Effects, beam, SV_I16),
    SAVE_FIELD(struct Effects, particle, SV_I16),
    SAVE_FIELD(struct Effects, explosion1, SV_I16),
    SAVE_FIELD(struct Effects, explosion2, SV_I16),
    SAVE_FIELD(struct Effects, spacing, SV_U16),
    SAVE_FIELD(struct Effects, sound_idx, SV_U16),
    SAVE_FIELD(struct Effects, sound_range, SV_U8),
);

SAVE_STRUCT(EffectsConfig, struct EffectsConfig,
    SAVE_SUB_ARRAY(struct EffectsConfig, effect_cfgstats, EffectConfigStats),
    SAVE_FIELD(struct EffectsConfig, effectgen_cfgstats_count, SV_I32),
    SAVE_SUB_ARRAY(struct EffectsConfig, effectgen_cfgstats, EffectGeneratorConfigStats),
    SAVE_SUB_ARRAY(struct EffectsConfig, effectelement_cfgstats, EffectElementConfigStats),
);

SAVE_STRUCT(FlameProperties, struct FlameProperties,
    SAVE_FIELD(struct FlameProperties, animation_id, SV_U16),
    SAVE_FIELD(struct FlameProperties, anim_speed, SV_I16),
    SAVE_FIELD(struct FlameProperties, sprite_size, SV_I32),
    SAVE_FIELD(struct FlameProperties, td_add_x, SV_I32),
    SAVE_FIELD(struct FlameProperties, td_add_y, SV_I32),
    SAVE_FIELD(struct FlameProperties, fp_add_x, SV_I32),
    SAVE_FIELD(struct FlameProperties, fp_add_y, SV_I32),
    SAVE_FIELD(struct FlameProperties, transparency_flags, SV_U8),
);

SAVE_STRUCT(GameRulesConfig, struct GameRulesConfig,
    SAVE_FIELD(struct GameRulesConfig, pot_of_gold_holds, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, chest_gold_hold, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, gold_pile_value, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, gold_pile_maximum, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, gold_per_hoard, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, bag_gold_hold, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, food_life_out_of_hatchery, SV_U16),
    SAVE_FIELD(struct GameRulesConfig, boulder_reduce_health_wall, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, boulder_reduce_health_slap, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, boulder_reduce_health_room, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, pay_day_gap, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, dungeon_heart_heal_time, SV_U32),
    SAVE_FIELD(struct GameRulesConfig, dungeon_heart_heal_health, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, hero_door_wait_time, SV_U32),
    SAVE_FIELD(struct GameRulesConfig, classic_bugs_flags, SV_U32),
    SAVE_FIELD(struct GameRulesConfig, door_sale_percent, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, room_sale_percent, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, trap_sale_percent, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, pay_day_speed, SV_U32),
    SAVE_FIELD(struct GameRulesConfig, allies_share_vision, SV_BOOL8),
    SAVE_FIELD(struct GameRulesConfig, allies_share_drop, SV_BOOL8),
    SAVE_FIELD(struct GameRulesConfig, allies_share_cta, SV_BOOL8),
    SAVE_FIELD(struct GameRulesConfig, allies_share_disease, SV_BOOL8),
    SAVE_FIELD(struct GameRulesConfig, winner_tortures_loser, SV_BOOL8),
    SAVE_FIELD(struct GameRulesConfig, display_portal_limit, SV_BOOL8),
    SAVE_FIELD(struct GameRulesConfig, max_things_in_hand, SV_U8),
    SAVE_FIELD(struct GameRulesConfig, torture_payday, SV_U16),
    SAVE_FIELD(struct GameRulesConfig, torture_training_cost, SV_I16),
    SAVE_FIELD(struct GameRulesConfig, torture_scavenging_cost, SV_I16),
    SAVE_FIELD(struct GameRulesConfig, easter_egg_speech_chance, SV_U32),
    SAVE_FIELD(struct GameRulesConfig, easter_egg_speech_interval, SV_U32),
    SAVE_FIELD(struct GameRulesConfig, global_ambient_light, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, thing_minimum_illumination, SV_I32),
    SAVE_FIELD(struct GameRulesConfig, light_enabled, SV_BOOL8),
    SAVE_FIELD(struct GameRulesConfig, creatures_count, SV_U16),
);

SAVE_STRUCT(HealthRulesConfig, struct HealthRulesConfig,
    SAVE_FIELD(struct HealthRulesConfig, hunger_health_loss, SV_I32),
    SAVE_FIELD(struct HealthRulesConfig, turns_per_hunger_health_loss, SV_U16),
    SAVE_FIELD(struct HealthRulesConfig, food_health_gain, SV_I32),
    SAVE_FIELD(struct HealthRulesConfig, torture_health_loss, SV_I32),
    SAVE_FIELD(struct HealthRulesConfig, turns_per_torture_health_loss, SV_U16),
);

SAVE_STRUCT(InitLight, struct InitLight,
    SAVE_FIELD(struct InitLight, radius, SV_I16),
    SAVE_FIELD(struct InitLight, intensity, SV_U8),
    SAVE_FIELD(struct InitLight, flags, SV_U8),
    SAVE_SUB(struct InitLight, mappos, Coord3d),
    SAVE_FIELD(struct InitLight, is_dynamic, SV_U8),
    SAVE_FIELD(struct InitLight, attached_slb, SV_U32),
);

SAVE_STRUCT(InstanceInfo, struct InstanceInfo,
    SAVE_FIELD(struct InstanceInfo, instant, SV_BOOL8),
    SAVE_FIELD(struct InstanceInfo, time, SV_I32),
    SAVE_FIELD(struct InstanceInfo, fp_time, SV_I32),
    SAVE_FIELD(struct InstanceInfo, action_time, SV_I32),
    SAVE_FIELD(struct InstanceInfo, fp_action_time, SV_I32),
    SAVE_FIELD(struct InstanceInfo, reset_time, SV_I32),
    SAVE_FIELD(struct InstanceInfo, fp_reset_time, SV_I32),
    SAVE_FIELD(struct InstanceInfo, graphics_idx, SV_U8),
    SAVE_FIELD(struct InstanceInfo, postal_priority, SV_I8),
    SAVE_FIELD(struct InstanceInfo, instance_property_flags, SV_I16),
    SAVE_FIELD(struct InstanceInfo, force_visibility, SV_I16),
    SAVE_FIELD(struct InstanceInfo, primary_target, SV_U8),
    SAVE_FIELD(struct InstanceInfo, func_idx, SV_U8),
    SAVE_ARRAY(struct InstanceInfo, func_params, SV_I32),
    SAVE_FIELD(struct InstanceInfo, range_min, SV_I32),
    SAVE_FIELD(struct InstanceInfo, range_max, SV_I32),
    SAVE_FIELD(struct InstanceInfo, symbol_spridx, SV_I32),
    SAVE_FIELD(struct InstanceInfo, tooltip_stridx, SV_I16),
    SAVE_FIELD(struct InstanceInfo, no_animation_loop, SV_BOOL8),
    SAVE_FIELD(struct InstanceInfo, validate_source_func, SV_U8),
    SAVE_ARRAY(struct InstanceInfo, validate_source_func_params, SV_I32),
    SAVE_FIELD(struct InstanceInfo, validate_target_func, SV_U8),
    SAVE_ARRAY(struct InstanceInfo, validate_target_func_params, SV_I32),
    SAVE_FIELD(struct InstanceInfo, search_func, SV_U8),
    SAVE_ARRAY(struct InstanceInfo, search_func_params, SV_I32),
    SAVE_FIELD(struct InstanceInfo, fp_allow_self_cast_while_frozen, SV_BOOL8),
    SAVE_FIELD(struct InstanceInfo, fp_allow_self_cast_when_chicken, SV_BOOL8),
);

SAVE_STRUCT(LuaFuncsConf, struct LuaFuncsConf,
    SAVE_ARRAY2(struct LuaFuncsConf, lua_funcs, SV_STR),  /* plain-char */
);

SAVE_STRUCT(MagicConfig, struct MagicConfig,
    SAVE_FIELD(struct MagicConfig, spell_types_count, SV_I32),
    SAVE_SUB_ARRAY(struct MagicConfig, spell_config, SpellConfig),
    SAVE_SUB_ARRAY(struct MagicConfig, spell_cfgstats, SpellConfigStats),
    SAVE_FIELD(struct MagicConfig, shot_types_count, SV_I32),
    SAVE_SUB_ARRAY(struct MagicConfig, shot_cfgstats, ShotConfigStats),
    SAVE_FIELD(struct MagicConfig, power_types_count, SV_I32),
    SAVE_SUB_ARRAY(struct MagicConfig, power_cfgstats, PowerConfigStats),
    SAVE_FIELD(struct MagicConfig, special_types_count, SV_I32),
    SAVE_SUB_ARRAY(struct MagicConfig, special_cfgstats, SpecialConfigStats),
    SAVE_SUB_ARRAY(struct MagicConfig, instance_info, InstanceInfo),
);

SAVE_STRUCT(MagicRulesConfig, struct MagicRulesConfig,
    SAVE_FIELD(struct MagicRulesConfig, hold_audience_time, SV_I32),
    SAVE_FIELD(struct MagicRulesConfig, armageddon_teleport_your_time_gap, SV_I32),
    SAVE_FIELD(struct MagicRulesConfig, armageddon_teleport_enemy_time_gap, SV_I32),
    SAVE_FIELD(struct MagicRulesConfig, armageddon_count_down, SV_I32),
    SAVE_FIELD(struct MagicRulesConfig, armageddon_duration, SV_I32),
    SAVE_FIELD(struct MagicRulesConfig, disease_transfer_percentage, SV_U8),
    SAVE_FIELD(struct MagicRulesConfig, disease_lose_percentage_health, SV_U8),
    SAVE_FIELD(struct MagicRulesConfig, disease_lose_health_time, SV_U8),
    SAVE_FIELD(struct MagicRulesConfig, min_distance_for_teleport, SV_I32),
    SAVE_FIELD(struct MagicRulesConfig, collapse_dungeon_damage, SV_I32),
    SAVE_FIELD(struct MagicRulesConfig, turns_per_collapse_dngn_dmg, SV_I32),
    SAVE_FIELD(struct MagicRulesConfig, friendly_fight_area_damage_percent, SV_I32),
    SAVE_FIELD(struct MagicRulesConfig, friendly_fight_area_range_percent, SV_I32),
    SAVE_FIELD(struct MagicRulesConfig, armageddon_teleport_neutrals, SV_BOOL8),
    SAVE_FIELD(struct MagicRulesConfig, weight_calculate_push, SV_I16),
    SAVE_FIELD(struct MagicRulesConfig, allow_instant_charge_up, SV_BOOL8),
);

SAVE_STRUCT(ManufactureData, struct ManufactureData,
    SAVE_FIELD(struct ManufactureData, tngclass, SV_U8),
    SAVE_FIELD(struct ManufactureData, tngmodel, SV_I16),
    SAVE_FIELD(struct ManufactureData, work_state, SV_I32),
    SAVE_FIELD(struct ManufactureData, tooltip_stridx, SV_I32),
    SAVE_FIELD(struct ManufactureData, bigsym_sprite_idx, SV_I32),
    SAVE_FIELD(struct ManufactureData, medsym_sprite_idx, SV_I32),
    SAVE_FIELD(struct ManufactureData, panel_tab_idx, SV_I32),
);

SAVE_STRUCT(ObjectConfigStats, struct ObjectConfigStats,
    SAVE_STRING(struct ObjectConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct ObjectConfigStats, model_flags, SV_U32),
    SAVE_FIELD(struct ObjectConfigStats, genre, SV_I32),
    SAVE_FIELD(struct ObjectConfigStats, map_icon, SV_I32),
    SAVE_FIELD(struct ObjectConfigStats, hand_icon, SV_I32),
    SAVE_SUB(struct ObjectConfigStats, object_picked_up_offset, PickedUpOffset),
    SAVE_FIELD(struct ObjectConfigStats, tooltip_stridx, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, tooltip_optional, SV_BOOL8),
    SAVE_FIELD(struct ObjectConfigStats, health, SV_I32),
    SAVE_FIELD(struct ObjectConfigStats, fall_acceleration, SV_I8),
    SAVE_FIELD(struct ObjectConfigStats, inertia_floor, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, inertia_air, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, light_unaffected, SV_I8),
    SAVE_FIELD(struct ObjectConfigStats, immobile, SV_I8),
    SAVE_SUB(struct ObjectConfigStats, ilght, InitLight),
    SAVE_FIELD(struct ObjectConfigStats, sprite_anim_idx, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, sprite_anim_idx_in_hand, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, anim_speed, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, size_xy, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, size_z, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, sprite_size_max, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, fp_smpl_idx, SV_U16),
    SAVE_FIELD(struct ObjectConfigStats, draw_class, SV_U8),
    SAVE_FIELD(struct ObjectConfigStats, destroy_on_lava, SV_U8),
    SAVE_FIELD(struct ObjectConfigStats, related_creatr_model, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, persistence, SV_U8),
    SAVE_FIELD(struct ObjectConfigStats, destroy_on_liquid, SV_BOOL8),
    SAVE_FIELD(struct ObjectConfigStats, rotation_flag, SV_U8),
    SAVE_FIELD(struct ObjectConfigStats, updatefn_idx, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, initial_state, SV_U8),
    SAVE_FIELD(struct ObjectConfigStats, random_start_frame, SV_U8),
    SAVE_FIELD(struct ObjectConfigStats, transparency_flags, SV_U8),
    SAVE_SUB(struct ObjectConfigStats, effect, Effects),
    SAVE_FIELD(struct ObjectConfigStats, lava_burn_effect, SV_I16),
    SAVE_FIELD(struct ObjectConfigStats, water_splash_effect, SV_I16),
    SAVE_SUB(struct ObjectConfigStats, flame, FlameProperties),
);

SAVE_STRUCT(ObjectsConfig, struct ObjectsConfig,
    SAVE_FIELD(struct ObjectsConfig, object_types_count, SV_I32),
    SAVE_SUB_ARRAY(struct ObjectsConfig, object_cfgstats, ObjectConfigStats),
    SAVE_ARRAY(struct ObjectsConfig, object_to_door_or_trap, SV_I16),
    SAVE_ARRAY(struct ObjectsConfig, object_to_power_artifact, SV_I16),
    SAVE_ARRAY(struct ObjectsConfig, object_to_special_artifact, SV_I16),
    SAVE_ARRAY(struct ObjectsConfig, workshop_object_class, SV_U8),
);

SAVE_STRUCT(PickedUpOffset, struct PickedUpOffset,
    SAVE_FIELD(struct PickedUpOffset, delta_x, SV_I16),
    SAVE_FIELD(struct PickedUpOffset, delta_y, SV_I16),
);

SAVE_STRUCT(PlayerStateConfig, struct PlayerStateConfig,
    SAVE_SUB_ARRAY(struct PlayerStateConfig, plrst_cfg_stats, PlayerStateConfigStats),
);

SAVE_STRUCT(PlayerStateConfigStats, struct PlayerStateConfigStats,
    SAVE_STRING(struct PlayerStateConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct PlayerStateConfigStats, pointer_group, SV_U8),
    SAVE_FIELD(struct PlayerStateConfigStats, stop_own_units, SV_BOOL8),
);

SAVE_STRUCT(PowerConfigStats, struct PowerConfigStats,
    SAVE_STRING(struct PowerConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct PowerConfigStats, artifact_model, SV_I16),
    SAVE_FIELD(struct PowerConfigStats, can_cast_flags, SV_U64),
    SAVE_FIELD(struct PowerConfigStats, config_flags, SV_U32),
    SAVE_FIELD(struct PowerConfigStats, overcharge_check_idx, SV_U8),
    SAVE_FIELD(struct PowerConfigStats, work_state, SV_U32),
    SAVE_FIELD(struct PowerConfigStats, parent_power, SV_U16),
    SAVE_FIELD(struct PowerConfigStats, bigsym_sprite_idx, SV_I16),
    SAVE_FIELD(struct PowerConfigStats, medsym_sprite_idx, SV_I16),
    SAVE_FIELD(struct PowerConfigStats, name_stridx, SV_U16),
    SAVE_FIELD(struct PowerConfigStats, tooltip_stridx, SV_U16),
    SAVE_FIELD(struct PowerConfigStats, select_sample_idx, SV_I16),
    SAVE_FIELD(struct PowerConfigStats, pointer_sprite_idx, SV_I16),
    SAVE_FIELD(struct PowerConfigStats, panel_tab_idx, SV_U32),
    SAVE_FIELD(struct PowerConfigStats, select_sound_idx, SV_U16),
    SAVE_FIELD(struct PowerConfigStats, cast_cooldown, SV_I16),
    SAVE_FIELD(struct PowerConfigStats, cost_formula, SV_U8),
    SAVE_FIELD(struct PowerConfigStats, spell_idx, SV_U16),
    SAVE_FIELD(struct PowerConfigStats, effect_id, SV_I16),
    SAVE_FIELD(struct PowerConfigStats, magic_use_func_idx, SV_I16),
    SAVE_FIELD(struct PowerConfigStats, creature_model, SV_I16),
    SAVE_ARRAY(struct PowerConfigStats, cost, SV_I32),
    SAVE_FIELD(struct PowerConfigStats, duration, SV_I32),
    SAVE_ARRAY(struct PowerConfigStats, strength, SV_I32),
);

SAVE_STRUCT(PowerHandConfig, struct PowerHandConfig,
    SAVE_SUB_ARRAY(struct PowerHandConfig, pwrhnd_cfg_stats, PowerHandConfigStats),
);

SAVE_STRUCT(PowerHandConfigStats, struct PowerHandConfigStats,
    SAVE_STRING(struct PowerHandConfigStats, code_name),  /* plain-char */
    SAVE_ARRAY(struct PowerHandConfigStats, anim_idx, SV_I16),
    SAVE_ARRAY(struct PowerHandConfigStats, anim_speed, SV_I16),
);

SAVE_STRUCT(RoomConfigStats, struct RoomConfigStats,
    SAVE_STRING(struct RoomConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct RoomConfigStats, name_stridx, SV_I32),
    SAVE_FIELD(struct RoomConfigStats, tooltip_stridx, SV_I32),
    SAVE_FIELD(struct RoomConfigStats, creature_creation_model, SV_I32),
    SAVE_FIELD(struct RoomConfigStats, assigned_slab, SV_U8),
    SAVE_FIELD(struct RoomConfigStats, synergy_slab, SV_I16),
    SAVE_FIELD(struct RoomConfigStats, storage_height, SV_I8),
    SAVE_FIELD(struct RoomConfigStats, flags, SV_U32),
    SAVE_FIELD(struct RoomConfigStats, roles, SV_U32),
    SAVE_FIELD(struct RoomConfigStats, panel_tab_idx, SV_I32),
    SAVE_FIELD(struct RoomConfigStats, bigsym_sprite_idx, SV_I32),
    SAVE_FIELD(struct RoomConfigStats, medsym_sprite_idx, SV_I32),
    SAVE_FIELD(struct RoomConfigStats, pointer_sprite_idx, SV_I32),
    SAVE_FIELD(struct RoomConfigStats, ambient_snd_smp_id, SV_U32),
    SAVE_SUB(struct RoomConfigStats, msg_needed, SpeechRef),
    SAVE_SUB(struct RoomConfigStats, msg_too_small, SpeechRef),
    SAVE_SUB(struct RoomConfigStats, msg_no_route, SpeechRef),
    SAVE_FIELD(struct RoomConfigStats, cost, SV_I16),
    SAVE_FIELD(struct RoomConfigStats, health, SV_I32),
    SAVE_FIELD(struct RoomConfigStats, update_total_capacity_idx, SV_I16),
    SAVE_FIELD(struct RoomConfigStats, update_storage_in_room_idx, SV_I16),
    SAVE_FIELD(struct RoomConfigStats, update_workers_in_room_idx, SV_I16),
);

SAVE_STRUCT(RoomRulesConfig, struct RoomRulesConfig,
    SAVE_FIELD(struct RoomRulesConfig, scavenge_cost_frequency, SV_I32),
    SAVE_FIELD(struct RoomRulesConfig, temple_scavenge_protection_turns, SV_U32),
    SAVE_FIELD(struct RoomRulesConfig, train_cost_frequency, SV_I32),
    SAVE_FIELD(struct RoomRulesConfig, ghost_convert_chance, SV_U8),
    SAVE_FIELD(struct RoomRulesConfig, default_generate_speed, SV_U16),
    SAVE_FIELD(struct RoomRulesConfig, default_max_crtrs_gen_entrance, SV_U32),
    SAVE_FIELD(struct RoomRulesConfig, food_generation_speed, SV_I32),
    SAVE_FIELD(struct RoomRulesConfig, prison_skeleton_chance, SV_U8),
    SAVE_FIELD(struct RoomRulesConfig, bodies_for_vampire, SV_U8),
    SAVE_FIELD(struct RoomRulesConfig, graveyard_convert_time, SV_U16),
    SAVE_FIELD(struct RoomRulesConfig, barrack_max_party_size, SV_I16),
    SAVE_FIELD(struct RoomRulesConfig, training_room_max_level, SV_U8),
    SAVE_FIELD(struct RoomRulesConfig, scavenge_good_allowed, SV_BOOL8),
    SAVE_FIELD(struct RoomRulesConfig, scavenge_neutral_allowed, SV_BOOL8),
    SAVE_FIELD(struct RoomRulesConfig, time_between_prison_break, SV_U32),
    SAVE_FIELD(struct RoomRulesConfig, prison_break_chance, SV_U8),
    SAVE_FIELD(struct RoomRulesConfig, torture_death_chance, SV_U8),
    SAVE_FIELD(struct RoomRulesConfig, torture_convert_chance, SV_U8),
    SAVE_FIELD(struct RoomRulesConfig, time_in_prison_without_break, SV_U32),
    SAVE_FIELD(struct RoomRulesConfig, train_efficiency, SV_U16),
    SAVE_FIELD(struct RoomRulesConfig, work_efficiency, SV_U16),
    SAVE_FIELD(struct RoomRulesConfig, scavenge_efficiency, SV_U16),
    SAVE_FIELD(struct RoomRulesConfig, research_efficiency, SV_U16),
);

SAVE_STRUCT(RulesConfig, struct RulesConfig,
    SAVE_SUB(struct RulesConfig, gameplay, GameRulesConfig),
    SAVE_SUB(struct RulesConfig, computer, ComputerRulesConfig),
    SAVE_SUB(struct RulesConfig, creature, CreatureRulesConfig),
    SAVE_SUB(struct RulesConfig, magic, MagicRulesConfig),
    SAVE_SUB(struct RulesConfig, rooms, RoomRulesConfig),
    SAVE_SUB(struct RulesConfig, workers, WorkersRulesConfig),
    SAVE_SUB(struct RulesConfig, health, HealthRulesConfig),
    SAVE_SUB(struct RulesConfig, sacrifices, SacrificesRulesConfig),
);

SAVE_STRUCT(SacrificeRecipe, struct SacrificeRecipe,
    SAVE_ARRAY(struct SacrificeRecipe, victims, SV_I16),
    SAVE_FIELD(struct SacrificeRecipe, action, SV_I32),
    SAVE_FIELD(struct SacrificeRecipe, param, SV_I32),
);

SAVE_STRUCT(SacrificesRulesConfig, struct SacrificesRulesConfig,
    SAVE_SUB_ARRAY(struct SacrificesRulesConfig, sacrifice_recipes, SacrificeRecipe),
    SAVE_FIELD(struct SacrificesRulesConfig, cheaper_diggers_sacrifice_model, SV_I16),
);

SAVE_STRUCT(ShotConfigStats, struct ShotConfigStats,
    SAVE_STRING(struct ShotConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct ShotConfigStats, model_flags, SV_U32),
    SAVE_FIELD(struct ShotConfigStats, health, SV_I32),
    SAVE_FIELD(struct ShotConfigStats, area_range, SV_I32),
    SAVE_FIELD(struct ShotConfigStats, area_damage, SV_I32),
    SAVE_FIELD(struct ShotConfigStats, area_hit_type, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, area_blow, SV_I32),
    SAVE_FIELD(struct ShotConfigStats, damage, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, speed, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, is_magical, SV_BOOL8),
    SAVE_SUB(struct ShotConfigStats, hit_generic, ShotHitConfig),
    SAVE_SUB(struct ShotConfigStats, hit_door, ShotHitConfig),
    SAVE_SUB(struct ShotConfigStats, hit_water, ShotHitConfig),
    SAVE_SUB(struct ShotConfigStats, hit_lava, ShotHitConfig),
    SAVE_SUB(struct ShotConfigStats, hit_creature, ShotHitConfig),
    SAVE_SUB(struct ShotConfigStats, dig, ShotHitConfig),
    SAVE_SUB(struct ShotConfigStats, hit_heart, ShotHitConfig),
    SAVE_SUB(struct ShotConfigStats, explode, ShotDetonateConfig),
    SAVE_SUB(struct ShotConfigStats, visual, ShotVisualConfig),
    SAVE_FIELD(struct ShotConfigStats, firing_sound, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, shot_sound, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, sound_priority, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, firing_sound_variants, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, max_range, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, sprite_anim_idx, SV_U16),
    SAVE_FIELD(struct ShotConfigStats, sprite_size_max, SV_U16),
    SAVE_FIELD(struct ShotConfigStats, size_xy, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, size_z, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, fall_acceleration, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, cast_spell_kind, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, push_on_hit, SV_I8),
    SAVE_FIELD(struct ShotConfigStats, destroy_on_first_hit, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, experience_given_to_shooter, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, inertia_floor, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, inertia_air, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, bounce_angle, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, target_hitstop_turns, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, animation_transparency, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, light_radius, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, light_intensity, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, light_flags, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, unshaded, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, soft_landing, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, effect_id, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, effect_bleeding, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, effect_frozen, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, fire_logic, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, update_logic, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, effect_spacing, SV_U16),
    SAVE_FIELD(struct ShotConfigStats, effect_amount, SV_U8),
    SAVE_FIELD(struct ShotConfigStats, periodical, SV_U16),
    SAVE_FIELD(struct ShotConfigStats, spread_xy, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, spread_z, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, speed_deviation, SV_I16),
    SAVE_FIELD(struct ShotConfigStats, hit_thing_lua_func_idx, SV_I16),
);

SAVE_STRUCT(ShotDetonateConfig, struct ShotDetonateConfig,
    SAVE_FIELD(struct ShotDetonateConfig, effect1_model, SV_I16),
    SAVE_FIELD(struct ShotDetonateConfig, effect2_model, SV_I16),
    SAVE_FIELD(struct ShotDetonateConfig, around_effect1_model, SV_I16),
    SAVE_FIELD(struct ShotDetonateConfig, around_effect2_model, SV_I16),
);

SAVE_STRUCT(ShotHitConfig, struct ShotHitConfig,
    SAVE_FIELD(struct ShotHitConfig, effect_model, SV_I16),
    SAVE_FIELD(struct ShotHitConfig, sndsample_idx, SV_I16),
    SAVE_FIELD(struct ShotHitConfig, sndsample_range, SV_U8),
    SAVE_FIELD(struct ShotHitConfig, withstand, SV_U8),
);

SAVE_STRUCT(ShotVisualConfig, struct ShotVisualConfig,
    SAVE_FIELD(struct ShotVisualConfig, effect_model, SV_I16),
    SAVE_FIELD(struct ShotVisualConfig, amount, SV_U8),
    SAVE_FIELD(struct ShotVisualConfig, random_range, SV_I16),
    SAVE_FIELD(struct ShotVisualConfig, shot_health, SV_I32),
);

SAVE_STRUCT(SlabConfigStats, struct SlabConfigStats,
    SAVE_STRING(struct SlabConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct SlabConfigStats, tooltip_stridx, SV_I32),
    SAVE_FIELD(struct SlabConfigStats, assigned_room, SV_U8),
    SAVE_FIELD(struct SlabConfigStats, block_flags_height, SV_I16),
    SAVE_FIELD(struct SlabConfigStats, block_health_index, SV_I16),
    SAVE_FIELD(struct SlabConfigStats, block_flags, SV_U32),
    SAVE_FIELD(struct SlabConfigStats, noblck_flags, SV_U32),
    SAVE_FIELD(struct SlabConfigStats, fill_style, SV_U8),
    SAVE_FIELD(struct SlabConfigStats, category, SV_U8),
    SAVE_FIELD(struct SlabConfigStats, slb_id, SV_U8),
    SAVE_FIELD(struct SlabConfigStats, wibble, SV_U8),
    SAVE_FIELD(struct SlabConfigStats, is_safe_land, SV_U8),
    SAVE_FIELD(struct SlabConfigStats, animated, SV_U8),
    SAVE_FIELD(struct SlabConfigStats, is_diggable, SV_U8),
    SAVE_FIELD(struct SlabConfigStats, wlb_type, SV_U8),
    SAVE_FIELD(struct SlabConfigStats, is_ownable, SV_U8),
    SAVE_FIELD(struct SlabConfigStats, indestructible, SV_U8),
    SAVE_FIELD(struct SlabConfigStats, gold_held, SV_I32),
);

SAVE_STRUCT(SlabsConfig, struct SlabsConfig,
    SAVE_FIELD(struct SlabsConfig, slab_types_count, SV_I32),
    SAVE_SUB_ARRAY(struct SlabsConfig, slab_cfgstats, SlabConfigStats),
    SAVE_FIELD(struct SlabsConfig, room_types_count, SV_I32),
    SAVE_SUB_ARRAY(struct SlabsConfig, room_cfgstats, RoomConfigStats),
);

SAVE_STRUCT(SpecialConfigStats, struct SpecialConfigStats,
    SAVE_STRING(struct SpecialConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct SpecialConfigStats, artifact_model, SV_I16),
    SAVE_FIELD(struct SpecialConfigStats, tooltip_stridx, SV_I32),
    SAVE_SUB(struct SpecialConfigStats, speech, SpeechRef),
    SAVE_FIELD(struct SpecialConfigStats, effect_id, SV_I16),
    SAVE_FIELD(struct SpecialConfigStats, value, SV_I16),
);

SAVE_STRUCT(SpeechRef, struct SpeechRef,
    SAVE_FIELD(struct SpeechRef, id, SV_I32),
    SAVE_STRING(struct SpeechRef, path),  /* plain-char */
);

SAVE_STRUCT(SpellConfig, struct SpellConfig,
    SAVE_FIELD(struct SpellConfig, cast_at_thing, SV_U8),
    SAVE_FIELD(struct SpellConfig, shot_model, SV_I16),
    SAVE_FIELD(struct SpellConfig, caster_affected, SV_U8),
    SAVE_FIELD(struct SpellConfig, cast_effect_model, SV_I16),
    SAVE_FIELD(struct SpellConfig, caster_affect_sound, SV_U16),
    SAVE_FIELD(struct SpellConfig, bigsym_sprite_idx, SV_I16),
    SAVE_FIELD(struct SpellConfig, medsym_sprite_idx, SV_I16),
    SAVE_FIELD(struct SpellConfig, cast_sound, SV_I16),
    SAVE_FIELD(struct SpellConfig, caster_sounds_count, SV_U8),
    SAVE_FIELD(struct SpellConfig, crtr_summon_model, SV_I16),
    SAVE_FIELD(struct SpellConfig, crtr_summon_level, SV_I16),
    SAVE_FIELD(struct SpellConfig, crtr_summon_amount, SV_I16),
    SAVE_FIELD(struct SpellConfig, linked_power, SV_U16),
    SAVE_FIELD(struct SpellConfig, countdown, SV_I32),
    SAVE_FIELD(struct SpellConfig, duration, SV_I32),
    SAVE_FIELD(struct SpellConfig, aura_effect, SV_I16),
    SAVE_FIELD(struct SpellConfig, aura_duration, SV_I32),
    SAVE_FIELD(struct SpellConfig, aura_frequency, SV_I32),
    SAVE_FIELD(struct SpellConfig, healing_recovery, SV_I32),
    SAVE_FIELD(struct SpellConfig, damage, SV_I32),
    SAVE_FIELD(struct SpellConfig, damage_frequency, SV_I32),
    SAVE_FIELD(struct SpellConfig, spell_flags, SV_U32),
    SAVE_FIELD(struct SpellConfig, cleanse_flags, SV_U32),
    SAVE_FIELD(struct SpellConfig, properties_flags, SV_U8),
);

SAVE_STRUCT(SpellConfigStats, struct SpellConfigStats,
    SAVE_STRING(struct SpellConfigStats, code_name),  /* plain-char */
);

SAVE_STRUCT(TrapConfigStats, struct TrapConfigStats,
    SAVE_STRING(struct TrapConfigStats, code_name),  /* plain-char */
    SAVE_FIELD(struct TrapConfigStats, name_stridx, SV_I32),
    SAVE_FIELD(struct TrapConfigStats, tooltip_stridx, SV_I32),
    SAVE_FIELD(struct TrapConfigStats, bigsym_sprite_idx, SV_I32),
    SAVE_FIELD(struct TrapConfigStats, medsym_sprite_idx, SV_I32),
    SAVE_FIELD(struct TrapConfigStats, pointer_sprite_idx, SV_I32),
    SAVE_FIELD(struct TrapConfigStats, panel_tab_idx, SV_I32),
    SAVE_FIELD(struct TrapConfigStats, manufct_level, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, manufct_required, SV_U32),
    SAVE_FIELD(struct TrapConfigStats, shots, SV_I32),
    SAVE_FIELD(struct TrapConfigStats, shots_delay, SV_I32),
    SAVE_FIELD(struct TrapConfigStats, initial_delay, SV_U16),
    SAVE_FIELD(struct TrapConfigStats, trigger_type, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, activation_type, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, activation_lua_func_idx, SV_I16),
    SAVE_FIELD(struct TrapConfigStats, created_itm_model, SV_U16),
    SAVE_FIELD(struct TrapConfigStats, activation_level, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, hit_type, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, hidden, SV_BOOL8),
    SAVE_FIELD(struct TrapConfigStats, slappable, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, detect_invisible, SV_BOOL8),
    SAVE_FIELD(struct TrapConfigStats, notify, SV_BOOL8),
    SAVE_FIELD(struct TrapConfigStats, place_on_bridge, SV_BOOL8),
    SAVE_FIELD(struct TrapConfigStats, place_on_subtile, SV_BOOL8),
    SAVE_FIELD(struct TrapConfigStats, instant_placement, SV_BOOL8),
    SAVE_FIELD(struct TrapConfigStats, remove_once_depleted, SV_BOOL8),
    SAVE_FIELD(struct TrapConfigStats, health, SV_I32),
    SAVE_FIELD(struct TrapConfigStats, destructible, SV_I8),
    SAVE_FIELD(struct TrapConfigStats, unstable, SV_I8),
    SAVE_FIELD(struct TrapConfigStats, destroyed_effect, SV_I16),
    SAVE_FIELD(struct TrapConfigStats, size_xy, SV_I16),
    SAVE_FIELD(struct TrapConfigStats, size_z, SV_I16),
    SAVE_FIELD(struct TrapConfigStats, sprite_anim_idx, SV_U32),
    SAVE_FIELD(struct TrapConfigStats, attack_sprite_anim_idx, SV_U32),
    SAVE_FIELD(struct TrapConfigStats, recharge_sprite_anim_idx, SV_U32),
    SAVE_FIELD(struct TrapConfigStats, sprite_size_max, SV_U32),
    SAVE_FIELD(struct TrapConfigStats, anim_speed, SV_U32),
    SAVE_FIELD(struct TrapConfigStats, attack_anim_speed, SV_U32),
    SAVE_FIELD(struct TrapConfigStats, recharge_anim_speed, SV_U32),
    SAVE_FIELD(struct TrapConfigStats, unanimated, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, unshaded, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, random_start_frame, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, flag_number, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, light_radius, SV_I16),
    SAVE_FIELD(struct TrapConfigStats, light_intensity, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, light_flag, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, transparency_flag, SV_U8),
    SAVE_FIELD(struct TrapConfigStats, shot_shift_x, SV_U16),
    SAVE_FIELD(struct TrapConfigStats, shot_shift_y, SV_U16),
    SAVE_FIELD(struct TrapConfigStats, shot_shift_z, SV_U16),
    SAVE_SUB(struct TrapConfigStats, shotvector, ComponentVector),
    SAVE_SUB(struct TrapConfigStats, flame, FlameProperties),
    SAVE_FIELD(struct TrapConfigStats, selling_value, SV_I32),
    SAVE_FIELD(struct TrapConfigStats, unsellable, SV_BOOL8),
    SAVE_FIELD(struct TrapConfigStats, place_sound_idx, SV_I16),
    SAVE_FIELD(struct TrapConfigStats, trigger_sound_idx, SV_I16),
    SAVE_FIELD(struct TrapConfigStats, updatefn_idx, SV_I16),
);

SAVE_STRUCT(TrapDoorConfig, struct TrapDoorConfig,
    SAVE_FIELD(struct TrapDoorConfig, trap_types_count, SV_I32),
    SAVE_SUB_ARRAY(struct TrapDoorConfig, trap_cfgstats, TrapConfigStats),
    SAVE_FIELD(struct TrapDoorConfig, door_types_count, SV_I32),
    SAVE_SUB_ARRAY(struct TrapDoorConfig, door_cfgstats, DoorConfigStats),
    SAVE_ARRAY(struct TrapDoorConfig, trap_to_object, SV_I16),
    SAVE_ARRAY(struct TrapDoorConfig, door_to_object, SV_I16),
    SAVE_FIELD(struct TrapDoorConfig, manufacture_types_count, SV_I32),
    SAVE_SUB_ARRAY(struct TrapDoorConfig, manufacture_data, ManufactureData),
);

SAVE_STRUCT(WorkersRulesConfig, struct WorkersRulesConfig,
    SAVE_FIELD(struct WorkersRulesConfig, hits_per_slab, SV_U8),
    SAVE_FIELD(struct WorkersRulesConfig, default_imp_dig_damage, SV_U32),
    SAVE_FIELD(struct WorkersRulesConfig, default_imp_dig_own_damage, SV_U32),
    SAVE_FIELD(struct WorkersRulesConfig, digger_work_experience, SV_I32),
    SAVE_FIELD(struct WorkersRulesConfig, drag_to_lair, SV_U16),
);
