/** @file schema_game.c
 *     Field tables for saved structs.
 */
#include "pre_inc.h"
#include "kfx/save/SaveTypes.h"
#include "game_legacy.h"
#include "game_merge.h"
#include "packets.h"
#include "config_campaigns.h"
#include "front_network.h"
#include "post_inc.h"
#include "kfx/save/core/save_schema.h"
#include "kfx/save/core/schema/save_tables_decl.h"

SAVE_STRUCT(DesyncChecksums, struct DesyncChecksums,
    SAVE_FIELD(struct DesyncChecksums, creatures, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, traps, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, shots, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, objects, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, effects, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, dead_creatures, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, effect_gens, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, doors, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, rooms, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, players, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, dig_tasks, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, action_seed, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, ai_seed, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, player_seed, SV_U32),
    SAVE_FIELD(struct DesyncChecksums, game_turn, SV_U32),
);

SAVE_STRUCT(Game, struct Game,
    SAVE_FIELD(struct Game, continue_level_number, SV_I32),
    SAVE_FIELD(struct Game, run_after_victory, SV_BOOL8),
    SAVE_FIELD(struct Game, operation_flags, SV_U8),
    SAVE_FIELD(struct Game, view_mode_flags, SV_U8),
    SAVE_FIELD(struct Game, flags_gui, SV_U8),
    SAVE_FIELD(struct Game, mode_flags, SV_U8),
    SAVE_FIELD(struct Game, eastegg01_cntr, SV_U8),
    SAVE_FIELD(struct Game, eastegg02_cntr, SV_U8),
    SAVE_FIELD(struct Game, music_track, SV_I8),
    SAVE_ARRAY_EX(struct Game, music_fname, SV_STR, .flags = SVF_SAVE),  /* plain-char */
    SAVE_FIELD(struct Game, save_game_slot, SV_I8),
    SAVE_FIELD(struct Game, selected_level_number, SV_I32),
    SAVE_FIELD_EX(struct Game, active_lens_type, SV_I8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, applied_lens_type, SV_U8, .flags = SVF_SAVE),
    SAVE_SUB_ARRAY(struct Game, players, PlayerInfo),
    SAVE_SUB_ARRAY_EX(struct Game, user_states, UserState, .flags = SVF_SAVE),
    SAVE_SUB_ARRAY(struct Game, columns_data, Column),
    SAVE_FIELD(struct Game, slabset_num, SV_U16),
    SAVE_SUB_ARRAY(struct Game, slabset, SlabSet),
    SAVE_FIELD(struct Game, slabobjs_num, SV_U16),
    SAVE_ARRAY(struct Game, slabobjs_idx, SV_I16),
    SAVE_SUB_ARRAY(struct Game, slabobjs, SlabObj),
    SAVE_FIELD(struct Game, land_map_start, SV_U8),
    SAVE_SUB(struct Game, lish, LightsShadows),
    SAVE_SUB_ARRAY(struct Game, cctrl_data, CreatureControl),
    SAVE_SUB_ARRAY(struct Game, things_data, Thing),
    SAVE_DERIVED(struct Game, navigation_map, "init_navigation"),
    SAVE_SUB_ARRAY(struct Game, map, Map),
    SAVE_SUB_ARRAY(struct Game, computer_task, ComputerTask),
    SAVE_SUB_ARRAY(struct Game, computer, Computer2),
    SAVE_SUB_ARRAY(struct Game, slabmap, SlabMap),
    SAVE_SUB_ARRAY(struct Game, rooms, Room),
    SAVE_SUB_ARRAY(struct Game, dungeon, Dungeon),
    SAVE_SUB_ARRAY(struct Game, thing_lists, StructureList),
    SAVE_FIELD(struct Game, unrevealed_column_idx, SV_I16),
    SAVE_FIELD_EX(struct Game, local_plyr_idx, SV_I8, .flags = SVF_SAVE),
    SAVE_STRING(struct Game, campaign_fname),  /* plain-char */
    SAVE_SUB_ARRAY(struct Game, event, Event),
    SAVE_DERIVED(struct Game, ceiling_height_max, "ceiling_set_info"),
    SAVE_DERIVED(struct Game, ceiling_height_min, "ceiling_set_info"),
    SAVE_DERIVED(struct Game, ceiling_dist, "ceiling_set_info"),
    SAVE_DERIVED(struct Game, ceiling_search_dist, "ceiling_set_info"),
    SAVE_DERIVED(struct Game, ceiling_step, "ceiling_set_info"),
    SAVE_ARRAY(struct Game, col_static_entries, SV_I16),
    SAVE_FIELD(struct Game, loaded_level_number, SV_I16),
    SAVE_ARRAY(struct Game, texture_animation, SV_I16),
    SAVE_FIELD(struct Game, texture_id, SV_U8),
    SAVE_ARRAY(struct Game, synced_free_things, SV_U16),
    SAVE_FIELD(struct Game, synced_free_things_count, SV_U16),
    SAVE_ARRAY(struct Game, unsynced_free_things, SV_U16),
    SAVE_FIELD(struct Game, unsynced_free_things_count, SV_U16),
    SAVE_FIELD(struct Game, play_gameturn, SV_U32),
    SAVE_FIELD(struct Game, action_random_seed, SV_U32),
    SAVE_FIELD(struct Game, timestamp, SV_I64),
    SAVE_FIELD(struct Game, timestamp_tz, SV_I32),
    SAVE_FIELD(struct Game, timestamp_turn, SV_U32),
    SAVE_FIELD(struct Game, ai_random_seed, SV_U32),
    SAVE_FIELD(struct Game, player_random_seed, SV_U32),
    SAVE_FIELD_EX(struct Game, unsync_random_seed, SV_U32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, sound_random_seed, SV_U32, .flags = SVF_SAVE),
    SAVE_FIELD(struct Game, something_light_x, SV_I32),
    SAVE_FIELD(struct Game, something_light_y, SV_I32),
    SAVE_FIELD(struct Game, time_delta, SV_U32),
    SAVE_DERIVED(struct Game, top_cube, "level setup"),
    SAVE_FIELD_EX(struct Game, small_map_state, SV_U8, .flags = SVF_SAVE),
    SAVE_SUB_EX(struct Game, mouse_light_pos, Coord3d, .flags = SVF_SAVE),
    SAVE_RUNTIME(struct Game, packets),
    SAVE_RUNTIME(struct Game, input_lag_turns),
    SAVE_FIELD(struct Game, human_players_count, SV_I8),
    SAVE_FIELD(struct Game, neutral_player_num, SV_I8),
    SAVE_SUB_ARRAY(struct Game, gold_lookup, GoldLookup),
    SAVE_FIELD(struct Game, ambient_sound_thing_idx, SV_U16),
    SAVE_ARRAY(struct Game, block_health, SV_I32),
    SAVE_FIELD(struct Game, entrance_room_id, SV_U16),
    SAVE_FIELD(struct Game, entrances_count, SV_U16),
    SAVE_FIELD(struct Game, nodungeon_creatr_list_start, SV_U16),
    SAVE_FIELD(struct Game, game_kind, SV_I32),  /* enum4 */
    SAVE_FIELD(struct Game, map_changed_for_navigation, SV_BOOL8),
    SAVE_DERIVED(struct Game, creature_scores, "init_creature_scores"),
    SAVE_SUB_ARRAY_EX(struct Game, bookmark, Bookmark, .flags = SVF_SAVE),
    SAVE_SUB(struct Game, pool, CreaturePool),
    SAVE_RUNTIME(struct Game, fast_forward),
    SAVE_RUNTIME(struct Game, frame_step),
    SAVE_FIELD(struct Game, paused_at_gameturn, SV_BOOL8),
    SAVE_ARRAY(struct Game, pay_day_progress, SV_I32),
    SAVE_SUB_EX(struct Game, sound_settings, SoundSettings, .flags = SVF_SAVE),
    SAVE_SUB_ARRAY(struct Game, battles, CreatureBattle),
    SAVE_ARRAY2_EX(struct Game, evntbox_text_objective, SV_STR, .flags = SVF_SAVE),  /* plain-char */
    SAVE_ARRAY_EX(struct Game, evntbox_text_buffer, SV_STR, .flags = SVF_SAVE),  /* plain-char */
    SAVE_SUB_EX(struct Game, evntbox_scroll_window, TextScrollWindow, .flags = SVF_SAVE),
    SAVE_FIELD(struct Game, flash_button_index, SV_I32),
    SAVE_FIELD(struct Game, loaded_swipe_idx, SV_I8),
    SAVE_FIELD(struct Game, active_messages_count, SV_U8),
    SAVE_FIELD(struct Game, active_script_var_count, SV_U8),
    SAVE_FIELD(struct Game, bonus_time, SV_I32),
    SAVE_SUB(struct Game, armageddon_mappos, Coord3d),
    SAVE_FIELD(struct Game, armageddon_cast_turn, SV_U32),
    SAVE_FIELD(struct Game, armageddon_over_turn, SV_U32),
    SAVE_FIELD(struct Game, armageddon_caster_idx, SV_I8),
    SAVE_FIELD_EX(struct Game, active_panel_mnu_idx, SV_I8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, comp_player_aggressive, SV_I8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, comp_player_defensive, SV_I8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, comp_player_construct, SV_I8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, comp_player_creatrsonly, SV_I8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, creatures_tend_imprison, SV_BOOL8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, creatures_tend_flee, SV_BOOL8, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, hand_over_subtile_x, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, hand_over_subtile_y, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, chosen_room_kind, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, chosen_room_spridx, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, chosen_room_tooltip, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, chosen_spell_type, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, chosen_spell_spridx, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, chosen_spell_tooltip, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, manufactr_element, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, manufactr_spridx, SV_I32, .flags = SVF_SAVE),
    SAVE_FIELD_EX(struct Game, manufactr_tooltip, SV_I32, .flags = SVF_SAVE),

    SAVE_SUB_EX(struct Game, conf, Configs, .flags = SVF_RUNTIME),
    SAVE_FIELD(struct Game, turn_last_checked_for_gold, SV_U32),
    SAVE_FIELD(struct Game, computer_chat_flags, SV_U16),
    SAVE_ARRAY2(struct Game, quick_messages, SV_STR),  /* plain-char */
    SAVE_SUB_ARRAY(struct Game, messages, GuiMessage),
    SAVE_SUB(struct Game, lightst, LightSystemState),
    SAVE_FIELD(struct Game, max_custom_box_kind, SV_U8),
    SAVE_FIELD(struct Game, current_player_turn, SV_U32),
    SAVE_FIELD(struct Game, script_current_player, SV_I32),
    SAVE_SUB(struct Game, triggered_object_location, Coord3d),
    SAVE_ARRAY2(struct Game, box_tooltip, SV_STR),  /* plain-char */
    SAVE_SUB_ARRAY(struct Game, fx_lines, ScriptFxLine),
    SAVE_FIELD(struct Game, active_fx_lines, SV_I32),
    SAVE_SUB_ARRAY(struct Game, action_points, ActionPoint),
    SAVE_FIELD(struct Game, last_level, SV_I32),
    SAVE_SUB(struct Game, script, LevelScript),
    SAVE_FIELD(struct Game, script_timer_player, SV_I8),
    SAVE_FIELD(struct Game, script_timer_id, SV_U8),
    SAVE_FIELD(struct Game, script_timer_limit, SV_U32),
    SAVE_FIELD(struct Game, timer_real, SV_BOOL8),
    SAVE_SUB_ARRAY(struct Game, script_variables, ScriptVariable),
    SAVE_FIELD(struct Game, heart_lost_display_message, SV_BOOL8),
    SAVE_FIELD(struct Game, heart_lost_quick_message, SV_BOOL8),
    SAVE_FIELD(struct Game, heart_lost_message_id, SV_U32),
    SAVE_FIELD(struct Game, heart_lost_message_target, SV_I32),
    SAVE_ARRAY(struct Game, slab_ext_data, SV_U8),
    SAVE_ARRAY(struct Game, slab_ext_data_initial, SV_U8),
    SAVE_RUNTIME(struct Game, delta_time),
    SAVE_RUNTIME(struct Game, process_turn_time),  /* long-double */
    SAVE_RUNTIME(struct Game, flash_button_time),
    SAVE_FIELD(struct Game, map_subtiles_x, SV_I32),
    SAVE_FIELD(struct Game, map_subtiles_y, SV_I32),
    SAVE_FIELD(struct Game, map_tiles_x, SV_I16),
    SAVE_FIELD(struct Game, map_tiles_y, SV_I16),
    SAVE_DERIVED(struct Game, navigation_map_size_x, "set_map_size"),
    SAVE_DERIVED(struct Game, navigation_map_size_y, "set_map_size"),
    SAVE_DERIVED(struct Game, around_map, "set_map_size"),
    SAVE_DERIVED(struct Game, around_slab, "set_map_size"),
    SAVE_DERIVED(struct Game, around_slab_eight, "set_map_size"),
    SAVE_DERIVED(struct Game, small_around_slab, "set_map_size"),
    SAVE_RUNTIME(struct Game, skip_initial_input_turns),
    SAVE_SUB_EX(struct Game, host_checksums, DesyncChecksums, .flags = SVF_SYNC),
    SAVE_SUB_EX(struct Game, log_snapshot, LogDetailedSnapshot, .flags = SVF_SYNC),
);

SAVE_STRUCT(GuiMessage, struct GuiMessage,
    SAVE_STRING(struct GuiMessage, text),  /* plain-char */
    SAVE_FIELD(struct GuiMessage, plyr_idx, SV_I16),
    SAVE_FIELD(struct GuiMessage, expiration_turn, SV_U32),
    SAVE_FIELD(struct GuiMessage, target_idx, SV_I16),
    SAVE_FIELD(struct GuiMessage, type, SV_I8),
    SAVE_FIELD(struct GuiMessage, icon_idx, SV_I16),
);

SAVE_STRUCT(LogDetailedSnapshot, struct LogDetailedSnapshot,
    SAVE_SUB_ARRAY(struct LogDetailedSnapshot, things, LogThingDesyncInfo),
    SAVE_FIELD(struct LogDetailedSnapshot, thing_count, SV_I32),
    SAVE_SUB_ARRAY(struct LogDetailedSnapshot, players, LogPlayerDesyncInfo),
    SAVE_FIELD(struct LogDetailedSnapshot, player_count, SV_I32),
    SAVE_SUB_ARRAY(struct LogDetailedSnapshot, rooms, LogRoomDesyncInfo),
    SAVE_FIELD(struct LogDetailedSnapshot, room_count, SV_I32),
    SAVE_SUB_ARRAY2(struct LogDetailedSnapshot, dig_tasks, MapTask),
    SAVE_ARRAY(struct LogDetailedSnapshot, dig_task_counts, SV_U16),
);

SAVE_STRUCT(LogPlayerDesyncInfo, struct LogPlayerDesyncInfo,
    SAVE_FIELD(struct LogPlayerDesyncInfo, id, SV_I8),
    SAVE_FIELD(struct LogPlayerDesyncInfo, instance_num, SV_U8),
    SAVE_FIELD(struct LogPlayerDesyncInfo, instance_remain_turns, SV_U32),
    SAVE_SUB(struct LogPlayerDesyncInfo, mappos, Coord3d),
    SAVE_FIELD(struct LogPlayerDesyncInfo, checksum, SV_U32),
);

SAVE_STRUCT(LogRoomDesyncInfo, struct LogRoomDesyncInfo,
    SAVE_FIELD(struct LogRoomDesyncInfo, index, SV_U16),
    SAVE_FIELD(struct LogRoomDesyncInfo, slabs_count, SV_U16),
    SAVE_FIELD(struct LogRoomDesyncInfo, central_stl_x, SV_I32),
    SAVE_FIELD(struct LogRoomDesyncInfo, central_stl_y, SV_I32),
    SAVE_FIELD(struct LogRoomDesyncInfo, efficiency, SV_U16),
    SAVE_FIELD(struct LogRoomDesyncInfo, used_capacity, SV_U16),
    SAVE_FIELD(struct LogRoomDesyncInfo, checksum, SV_U32),
);

SAVE_STRUCT(LogThingDesyncInfo, struct LogThingDesyncInfo,
    SAVE_FIELD(struct LogThingDesyncInfo, index, SV_U16),
    SAVE_FIELD(struct LogThingDesyncInfo, class_id, SV_U8),
    SAVE_FIELD(struct LogThingDesyncInfo, model, SV_I16),
    SAVE_FIELD(struct LogThingDesyncInfo, owner, SV_I8),
    SAVE_SUB(struct LogThingDesyncInfo, mappos, Coord3d),
    SAVE_FIELD(struct LogThingDesyncInfo, health, SV_I32),
    SAVE_FIELD(struct LogThingDesyncInfo, creation_turn, SV_U32),
    SAVE_FIELD(struct LogThingDesyncInfo, random_seed, SV_U32),
    SAVE_FIELD(struct LogThingDesyncInfo, anim_sprite, SV_U16),
    SAVE_FIELD(struct LogThingDesyncInfo, anim_speed, SV_I16),
    SAVE_FIELD(struct LogThingDesyncInfo, anim_time, SV_I32),
    SAVE_FIELD(struct LogThingDesyncInfo, current_frame, SV_U8),
    SAVE_FIELD(struct LogThingDesyncInfo, max_frames, SV_U8),
    SAVE_FIELD(struct LogThingDesyncInfo, active_state, SV_U8),
    SAVE_FIELD(struct LogThingDesyncInfo, continue_state, SV_U8),
    SAVE_FIELD(struct LogThingDesyncInfo, movement_flags, SV_U16),
    SAVE_FIELD(struct LogThingDesyncInfo, move_angle_xy, SV_I16),
    SAVE_FIELD(struct LogThingDesyncInfo, move_angle_z, SV_I16),
    SAVE_FIELD(struct LogThingDesyncInfo, holding_player, SV_I8),
    SAVE_FIELD(struct LogThingDesyncInfo, parent_idx, SV_I16),
    SAVE_FIELD(struct LogThingDesyncInfo, fall_acceleration, SV_U8),
    SAVE_SUB(struct LogThingDesyncInfo, veloc_base, CoordDelta3d),
    SAVE_SUB(struct LogThingDesyncInfo, veloc_push_once, CoordDelta3d),
    SAVE_SUB(struct LogThingDesyncInfo, veloc_push_add, CoordDelta3d),
    SAVE_FIELD(struct LogThingDesyncInfo, is_special_digger, SV_BOOL8),
    SAVE_SUB(struct LogThingDesyncInfo, digger_moveto_pos, Coord3d),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_dragtng_idx, SV_I16),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_arming_thing_id, SV_U16),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_pickup_object_id, SV_U16),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_pickup_creature_id, SV_U16),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_move_flags, SV_U8),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_stack_update_turn, SV_I32),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_working_stl, SV_I32),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_task_stl, SV_I32),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_task_idx, SV_U16),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_consecutive_reinforcements, SV_U8),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_last_did_job, SV_U8),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_task_stack_pos, SV_U8),
    SAVE_FIELD(struct LogThingDesyncInfo, digger_task_repeats, SV_U16),
    SAVE_FIELD(struct LogThingDesyncInfo, checksum, SV_U32),
);

SAVE_STRUCT(SoundSettings, struct SoundSettings,
    SAVE_RUNTIME(struct SoundSettings, sound_data_path),  /* pointer */
    SAVE_RUNTIME(struct SoundSettings, music_data_path),  /* pointer */
    SAVE_RUNTIME(struct SoundSettings, dir3),  /* pointer */
    SAVE_FIELD(struct SoundSettings, sound_type, SV_U16),
    SAVE_FIELD(struct SoundSettings, flags, SV_U16),
    SAVE_FIELD(struct SoundSettings, max_number_of_samples, SV_U8),
    SAVE_FIELD(struct SoundSettings, stereo, SV_U8),
    SAVE_FIELD(struct SoundSettings, sound_buffer_enable, SV_U8),
    SAVE_FIELD(struct SoundSettings, danger_music, SV_U8),
    SAVE_FIELD(struct SoundSettings, no_load_sounds, SV_U8),
    SAVE_FIELD(struct SoundSettings, no_load_music, SV_U8),
    SAVE_FIELD(struct SoundSettings, sound_debug_mode, SV_U8),
    SAVE_FIELD(struct SoundSettings, sound_system, SV_U8),
    SAVE_FIELD(struct SoundSettings, audio_device_enable, SV_U8),
    SAVE_FIELD(struct SoundSettings, redbook_enable, SV_U8),
);

SAVE_STRUCT(TextScrollWindow, struct TextScrollWindow,
    SAVE_STRING(struct TextScrollWindow, text),  /* plain-char */
    SAVE_FIELD(struct TextScrollWindow, start_y, SV_I32),
    SAVE_FIELD(struct TextScrollWindow, action, SV_I8),
    SAVE_FIELD(struct TextScrollWindow, text_height, SV_I32),
    SAVE_FIELD(struct TextScrollWindow, window_height, SV_I32),
);
