[CAMPAIGN_ASSMIST]
ENG = "Assmist Isle"
CHI = "亚米斯特岛战役"
#CHT = 
#CZE = 
#DUT = 
#FRE = 
GER = "Assmist Isle"
#ITA = 
JPN = "アッスミスト島"
KOR = "애스미스트 섬"
LAT = "Insula Auxiliata"
#POL = 
POR = "Ilha da Névoa"
RUS = "Остров Эсмист"
SPA = "La Isla Asistida"
#SWE = 
UKR = "Острів Сракоміст"