/******************************************************************************/
// Free implementation of Bullfrog's Dungeon Keeper strategy game.
/******************************************************************************/
/** @file config_strings.h
 *     Header file for config_strings.c.
 * @par Purpose:
 *     List of language-specific strings support.
 * @par Comment:
 *     Just a header file - #defines, typedefs, function prototypes etc.
 * @author   Tomasz Lis
 * @date     25 May 2009 - 31 Jul 2009
 * @par  Copying and copyrights:
 *     This program is free software; you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation; either version 2 of the License, or
 *     (at your option) any later version.
 */
/******************************************************************************/
#ifndef DK_CFGSTRINGS_H
#define DK_CFGSTRINGS_H

#include "globals.h"
#include "bflib_basics.h"

#ifdef __cplusplus
extern "C" {
#endif
/******************************************************************************/
#define STRINGS_MAX       2000
#define GUI_STRINGS_COUNT (GuiStrEnd - TRANSLATION_STRINGS_START)
#define MAX_TOML_TRANSLATION_ENTRIES 2000

#define TRANSLATION_STRINGS_START STRINGS_MAX
#define GUI_STRINGS_START (STRINGS_MAX + MAX_TOML_TRANSLATION_ENTRIES)

struct GameCampaign;

enum GUIStrings {
    GUIStr_SuccessLandIsYours = GUI_STRINGS_START+0, // per-campaign
    GUIStr_LevelEventMessage = GUI_STRINGS_START+1, // range 1..200, per-campaign
    GUIStr_Empty = GUI_STRINGS_START+201,
    GUIStr_NameAndHealthDesc = GUI_STRINGS_START+222,
    GUIStr_ExperienceDesc,
    GUIStr_HungerDesc,
    GUIStr_Cancel,
    GUIStr_CreatureQueryDesc = GUI_STRINGS_START+287,
    GUIStr_SelectGame,
    GUIStr_NetworkMenu,
    GUIStr_MainMenu,
    GUIStr_CreatureAngerDesc = GUI_STRINGS_START+291,
    GUIStr_CreatureKillsDesc,
    GUIStr_CreatureStrengthDesc,
    GUIStr_CreatureWageDesc,
    GUIStr_CreatureGoldHeldDesc,
    GUIStr_CreatureDefenceDesc,
    GUIStr_CreatureSkillDesc,
    GUIStr_CreatureTimeInDungeonDesc,
    GUIStr_CreatureDexterityDesc,
    GUIStr_CreatureLuckDesc,
    GUIStr_CreatureBloodTypeDesc,
    GUIStr_CreatureIdleDesc,
    GUIStr_CreatureWorkingDesc,
    GUIStr_CreatureFightingDesc,
    GUIStr_CreatureFightDesc,
    GUIStr_CreatureFleeDesc,
    GUIStr_CreatureImprisonDesc,
    GUIStr_CreatureDefendingDesc,
    GUIStr_ConfirmYouSure = GUI_STRINGS_START+309,
    GUIStr_ConfirmYes,
    GUIStr_ConfirmNo,
    GUIStr_For,
    GUIStr_OptionShadowsDesc = GUI_STRINGS_START+313,
    GUIStr_OptionViewTypeDesc,
    GUIStr_OptionWallHeightDesc,
    GUIStr_OptionViewDistanceDesc,
    GUIStr_OptionGammaCorrectionDesc,
    GUIStr_Of,
    GUIStr_PausedMsg = GUI_STRINGS_START+320,
    GUIStr_PaneZoomInDesc,
    GUIStr_PaneZoomOutDesc,
    GUIStr_PaneLargeMapDesc,
    GUIStr_PaneMore = GUI_STRINGS_START+333,
    GUIStr_RecMovie = GUI_STRINGS_START+336,
    GUIStr_RecMovieFail,
    GUIStr_RecMovieDone,
    GUIStr_OptionSoundFx = GUI_STRINGS_START+340,
    GUIStr_OptionMusic,
    GUIStr_SlotUnused = GUI_STRINGS_START+342,
    GUIStr_MnuMainMenu = GUI_STRINGS_START+343,
    GUIStr_MnuLoadMenu,
    GUIStr_MnuLoadGame,
    GUIStr_MnuContinueGame,
    GUIStr_MnuMultiplayer = GUI_STRINGS_START+347,
    GUIStr_MnuReturnToMain,
    GUIStr_MnuPlayIntro,
    GUIStr_NetServiceMenu,
    GUIStr_NetSessionMenu,
    GUIStr_NetSpeed = GUI_STRINGS_START+352,
    GUIStr_NetComPort,
    GUIStr_NetPhoneNumber,
    GUIStr_NetIrq,
    GUIStr_MnuStatistics = GUI_STRINGS_START+356,
    GUIStr_LevelCompleted = GUI_STRINGS_START+357,
    GUIStr_MnuUnused = GUI_STRINGS_START+358,
    GUIStr_MnuQuit = GUI_STRINGS_START+359,
    GUIStr_MnuStartNewGame = GUI_STRINGS_START+360,
    GUIStr_TastyHeroes = GUI_STRINGS_START+361,
    GUIStr_CreditsHead1 = GUI_STRINGS_START+362, // range 362..394
    GUIStr_NetSessions = GUI_STRINGS_START+395,
    GUIStr_NetName,
    GUIStr_NetServices,
    GUIStr_NetMessages,
    GUIStr_NetCreateGame,
    GUIStr_NetJoinGame,
    GUIStr_NetStartGame,
    GUIStr_MnuOnlineLobbies = GUI_STRINGS_START+402,
    GUIStr_MnuCancel,
    GUIStr_MnuNoName,
    GUIStr_MnuPlayers,
    GUIStr_MnuLevel,
    GUIStr_MnuLevels,
    GUIStr_MnuGames = GUI_STRINGS_START+408,
    GUIStr_NetModemMenu = GUI_STRINGS_START+409,
    GUIStr_NetSerialMenu,
    GUIStr_NetInit = GUI_STRINGS_START+411,
    GUIStr_NetHangup,
    GUIStr_NetClear,
    GUIStr_NetAnswer,
    GUIStr_NetStart,
    GUIStr_NetAlly = GUI_STRINGS_START+416,
    GUIStr_NetAlliance,
    GUIStr_Credits = GUI_STRINGS_START+418,
    GUIStr_MnuOk = GUI_STRINGS_START+419,
    GUIStr_SpecRevealMapDesc = GUI_STRINGS_START+420,
    GUIStr_SpecResurrectCreatureDesc,
    GUIStr_SpecTransferCreatureDesc,
    GUIStr_SpecStealHeroDesc,
    GUIStr_SpecMultiplyCreaturesDesc,
    GUIStr_SpecIncreaseLevelDesc,
    GUIStr_SpecMakeSafeDesc,
    GUIStr_SpecLocateHiddenWorldDesc,
    GUIStr_SpecResurrectCreature,
    GUIStr_SpecTransferCreature,
    GUIStr_MnuHighScoreTable = GUI_STRINGS_START+431,
    GUIStr_GoToQueryMode,
    GUIStr_MoreInformation = GUI_STRINGS_START+433,
    GUIStr_BackToMainQueryScreen,
    GUIStr_SelectedAction,
    GUIStr_TeamChooseParty = GUI_STRINGS_START+436,
    GUIStr_TeamEnterDungeon,
    GUIStr_TeamPartyMembers,
    GUIStr_TeamAvailCreatures,
    GUIStr_TeamCreature,
    GUIStr_TeamMoneyAvailable,
    GUIStr_TeamLeader,
    GUIStr_TeamHire,
    GUIStr_TeamFire,
    GUIStr_TeamCost,
    GUIStr_TeamType,
    GUIStr_InformationPanelDesc = GUI_STRINGS_START+447,
    GUIStr_RoomPanelDesc = GUI_STRINGS_START+448,
    GUIStr_ResearchPanelDesc = GUI_STRINGS_START+449,
    GUIStr_WorkshopPanelDesc = GUI_STRINGS_START+450,
    GUIStr_CreaturePanelDesc = GUI_STRINGS_START+451,
    GUIStr_ResearchTimeDesc = GUI_STRINGS_START+452,
    GUIStr_WorkshopTimeDesc = GUI_STRINGS_START+453,
    GUIStr_PayTimeDesc = GUI_STRINGS_START+454,
    GUIStr_NumberOfRoomsDesc = GUI_STRINGS_START+455,
    GUIStr_NumberOfCreaturesDesc = GUI_STRINGS_START+456,
    GUIStr_TeamChooseGame,
    GUIStr_TeamGameType,
    GUIStr_TeamKeeperVsKeeper,
    GUIStr_TeamKeeperVsHeroes,
    GUIStr_TeamDeathmatch,
    GUIStr_SellRoomDesc = GUI_STRINGS_START+462,
    GUIStr_SellItemDesc,
    GUIStr_NextBattleDesc,
    GUIStr_CloseWindow,
    GUIStr_ZoomToArea,
    GUIStr_NoMouseInstalled,
    GUIStr_DefineKeys,
    GUIStr_AllyWithPlayer,
    GUIStr_PressAKey = GUI_STRINGS_START+470,
    GUIStr_CtrlUp,
    GUIStr_CtrlDown,
    GUIStr_CtrlLeft,
    GUIStr_CtrlRight,
    GUIStr_CtrlRotate,
    GUIStr_CtrlSpeed,
    GUIStr_CtrlRotateLeft,
    GUIStr_CtrlRotateRight,
    GUIStr_CtrlZoomIn,
    GUIStr_CtrlZoomOut,
    GUIStr_KeyLeftControl = GUI_STRINGS_START+481,
    GUIStr_KeyRightControl,
    GUIStr_KeyLeftShift,
    GUIStr_KeyRightShift,
    GUIStr_KeyLeftAlt,
    GUIStr_KeyRightAlt,
    GUIStr_KeySpace,
    GUIStr_KeyReturn,
    GUIStr_KeyTab,
    GUIStr_KeyCapsLock = GUI_STRINGS_START+490,
    GUIStr_KeyBackspace,
    GUIStr_KeyInsert,
    GUIStr_KeyDelete,
    GUIStr_KeyHome,
    GUIStr_KeyEnd,
    GUIStr_KeyPageUp,
    GUIStr_KeyPageDown,
    GUIStr_KeyNumLock = GUI_STRINGS_START+498,
    GUIStr_KeyNumSlash,
    GUIStr_KeyNumMul,
    GUIStr_KeyNumSub,
    GUIStr_KeyNumAdd,
    GUIStr_KeyNumEnter,
    GUIStr_KeyNumDelete,
    GUIStr_KeyNum1,
    GUIStr_KeyNum2,
    GUIStr_KeyNum3,
    GUIStr_KeyNum4,
    GUIStr_KeyNum5,
    GUIStr_KeyNum6,
    GUIStr_KeyNum7,
    GUIStr_KeyNum8,
    GUIStr_KeyNum9,
    GUIStr_KeyNum0,
    GUIStr_KeyF1 = GUI_STRINGS_START+515,
    GUIStr_KeyF2,
    GUIStr_KeyF3,
    GUIStr_KeyF4,
    GUIStr_KeyF5,
    GUIStr_KeyF6,
    GUIStr_KeyF7,
    GUIStr_KeyF8,
    GUIStr_KeyF9,
    GUIStr_KeyF10,
    GUIStr_KeyF11,
    GUIStr_KeyF12,
    GUIStr_KeyUp,
    GUIStr_KeyDown,
    GUIStr_KeyLeft,
    GUIStr_KeyRight,
    GUIStr_VersionMismatch = GUI_STRINGS_START+531,
    GUIStr_NetConnectnModem,
    GUIStr_NetDial,
    GUIStr_NetContinue,
    GUIStr_NetLineEngaged,
    GUIStr_NetUnknownError,
    GUIStr_NetNoCarrier,
    GUIStr_NetNoDialTone,
    GUIStr_NetNoResponse,
    GUIStr_NetNoServer,
    GUIStr_NetUnableToInit = GUI_STRINGS_START+541,
    GUIStr_NetUnableToCrGame,
    GUIStr_NetUnableToJoin,
    GUIStr_CompAssNowAggressive = GUI_STRINGS_START+548,
    GUIStr_CompAssNowDefensive,
    GUIStr_CompAssNowConstruction,
    GUIStr_CompAssNowMoveOnly,
    GUIStr_StateFight = GUI_STRINGS_START+567,
    GUIStr_StateAnnoyed = GUI_STRINGS_START+568,
    GUIStr_KeyShift = GUI_STRINGS_START+569,
    GUIStr_KeyControl,
    GUIStr_KeyAlt,
    GUIStr_CreditsHead2 = GUI_STRINGS_START+572, // range 572..577
    GUIStr_Lair=GUI_STRINGS_START+609,
    GUIStr_EventTreasureRoomFull = GUI_STRINGS_START+664,
    GUIStr_EventScavengingDetected,
    GUIStr_EventCreaturePayday,
    GUIStr_EventNewSpellPickedUp,
    GUIStr_EventNewRoomTakenOver,
    GUIStr_EventAreaDiscovered,
    GUIStr_EventInformation = GUI_STRINGS_START+670,
    GUIStr_EventRoomLost,
    GUIStr_EventHeartAttacked,
    GUIStr_EventFight,
    GUIStr_EventObjective,
    GUIStr_EventBreach,
    GUIStr_EventNewSpellResearched,
    GUIStr_EventNewRoomResearched = GUI_STRINGS_START+677,
    GUIStr_EventNewTrap,
    GUIStr_EventNewDoor,
    GUIStr_EventNewCreature = GUI_STRINGS_START+680,
    GUIStr_EventCreatureAnnoyed,
    GUIStr_EventNoMoreLivingSpace,
    GUIStr_EventAlarmTriggered,
    GUIStr_EventRoomUnderAttack,
    GUIStr_EventTreasureRoomNeeded,
    GUIStr_EventCreaturesHungry,
    GUIStr_EventTrapCrateFound,
    GUIStr_EventDoorCrateFound,
    GUIStr_EventDnSpecialFound = GUI_STRINGS_START+689,
    GUIStr_EventTreasrRoomFullDesc = GUI_STRINGS_START+690,
    GUIStr_EventCreatrScavngDesc,
    GUIStr_EventCreaturePaydayDesc,
    GUIStr_EventSpellPickedUpDesc,
    GUIStr_EventRoomTakenOverDesc,
    GUIStr_EventAreaDiscoveredDesc,
    GUIStr_EventInformationDesc,
    GUIStr_EventRoomLostDesc,
    GUIStr_EventDnHeartAttackedDesc = GUI_STRINGS_START+698,
    GUIStr_EventFightDesc,
    GUIStr_EventObjectiveDesc = GUI_STRINGS_START+700,
    GUIStr_EventBreachDesc,
    GUIStr_EventNewSpellResrchDesc,
    GUIStr_EventNewRoomResrchDesc,
    GUIStr_EventNewTrapDesc,
    GUIStr_EventNewDoorDesc,
    GUIStr_EventNewCreatureDesc,
    GUIStr_EventCreatrAnnoyedDesc,
    GUIStr_EventNoMoreLivingSetDesc,
    GUIStr_EventAlarmTriggeredDesc,
    GUIStr_EventRoomUnderAttackDesc = GUI_STRINGS_START+710,
    GUIStr_EventNeedTreasrRoomDesc,
    GUIStr_EventCreaturesHungryDesc,
    GUIStr_EventTrapCrateFoundDesc,
    GUIStr_EventDoorCrateFoundDesc,
    GUIStr_EventDnSpecialFoundDesc = GUI_STRINGS_START+715,
    GUIStr_MnuOptions = GUI_STRINGS_START+716,
    GUIStr_MnuGraphicsOptions,
    GUIStr_MnuSoundOptions,
    GUIStr_MnuLoad,
    GUIStr_MnuSave,
    GUIStr_MnuComputerAssist,
    GUIStr_MnuOptionsDesc = GUI_STRINGS_START+722,
    GUIStr_GraphicsMenuDesc = GUI_STRINGS_START+723,
    GUIStr_SoundMenuDesc,
    GUIStr_LoadGameDesc,
    GUIStr_SaveGameDesc,
    GUIStr_QuitGameDesc = GUI_STRINGS_START+727,
    GUIStr_ComputerAssistDesc = GUI_STRINGS_START+728,
    GUIStr_AggressiveAssistDesc,
    GUIStr_DefensiveAssistDesc,
    GUIStr_ConstructionAssistDesc,
    GUIStr_MoveOnlyAssistDesc,
    GUIStr_PickCreatrMostExpDesc = GUI_STRINGS_START+733,
    GUIStr_PickCreatrIdleDesc,
    GUIStr_PickCreatrWorkingDesc,
    GUIStr_PickCreatrFightingDesc,
    GUIStr_OptionsInvertMouse = GUI_STRINGS_START+737,
    GUIStr_OptionsPossessMouseSensitivity,
    GUIStr_OptionsMoreSensitive,
    GUIStr_OptionsLessSensitive = GUI_STRINGS_START+740,
    GUIStr_StatisticsNames1 = GUI_STRINGS_START+741, // range 741..802
    GUIStr_EasterPoems = GUI_STRINGS_START+803, // range 803..828
    GUIStr_GameHints = GUI_STRINGS_START+829, // range 829..839
    GUIStr_MnuRetToOptions = GUI_STRINGS_START+840,
    GUIStr_MnuExit = GUI_STRINGS_START+841,
    GUIStr_MnuAudio,
    GUIStr_MnuInvertMouse,
    GUIStr_MnuMouseSensitivity,
    GUIStr_MnuComputer,
    GUIStr_MnuComputerPlayers,
    GUIStr_On = GUI_STRINGS_START+847,
    GUIStr_Off = GUI_STRINGS_START+848,
    GUIStr_Sensitivity,
    GUIStr_MouseOptions,
    GUIStr_Mouse,
    GUIStr_UndoPickup,
    GUIStr_Pause,
    GUIStr_Map = GUI_STRINGS_START+854,
    GUIStr_InsufficientMemory,
    GUIStr_UnableToChangeRes,
    GUIStr_Query = GUI_STRINGS_START+857,
    GUIStr_CreditsHead3 = GUI_STRINGS_START+858, // range 858..867
    GUIStr_NetAttemptingToJoin = GUI_STRINGS_START+868,
    GUIStr_NetResyncing,
    GUIStr_Net1Player = GUI_STRINGS_START+870,
    GUIStr_Net2Players,
    GUIStr_Net3Players,
    GUIStr_Net4Players,
    GUIStr_NetOnline = GUI_STRINGS_START+874,
    GUIStr_NetLan,
    GUIStr_NetServiceSkirmish,
    GUIStr_MapN = GUI_STRINGS_START+877,
    GUIStr_MapE,
    GUIStr_MapS,
    GUIStr_MapW,
    GUIStr_Vs = GUI_STRINGS_START+881,
    GUIStr_CreditsHead4 = GUI_STRINGS_START+882, // range 882..884
    GUIStr_HappyBirthday = GUI_STRINGS_START+885,
    GUIStr_Error,
    GUIStr_ErrorSaving,
    GUIStr_NewLevels = GUI_STRINGS_START+888,
    GUIStr_TrapAvailable = GUI_STRINGS_START+889,
    GUIStr_TrapWorkshopNeeded,
    GUIStr_TrapUnavailable,
    GUIStr_LevelEventMessageDD = GUI_STRINGS_START+892, // range 892..940, Deeper Dungeons
    GUIStr_EventSecretDoorDiscovDesc = GUI_STRINGS_START+937,
    GUIStr_EventSecretDoorDiscovered,
    GUIStr_EventSecretDoorSpottedDesc,
    GUIStr_EventSecretDoorSpotted,
    GUIStr_MnuFreePlayLevels = GUI_STRINGS_START+941,
    GUIStr_MnuLandSelection = GUI_STRINGS_START+942,
    GUIStr_MnuCampaigns = GUI_STRINGS_START+943,
    GUIStr_MnuAddComputer = GUI_STRINGS_START+944,
    GUIStr_EventWorkRoomUnreachbl,
    GUIStr_EventWorkRoomUnreachblDesc,
    GUIStr_EventStorgRoomUnreachbl,
    GUIStr_EventStorgRoomUnreachblDesc,
    GUIStr_CreatureArmourDesc = GUI_STRINGS_START+949,
    GUIStr_CreatureSpeedDesc,
    GUIStr_CreatureLoyaltyDesc,
    GUIStr_CreatureResrchSkillDesc,
    GUIStr_CreatureManfctrSkillDesc,
    GUIStr_CreatureTraingSkillDesc,
    GUIStr_CreatureScavngSkillDesc,
    GUIStr_CreatureTraingCostDesc,
    GUIStr_CreatureScavngCostDesc,
    GUIStr_CreatureBestDmgDesc,
    GUIStr_CreatureWeightDesc,
    GUIStr_CreatureScoreDesc = GUI_STRINGS_START+960,
    GUIStr_CreatureHealthDesc = GUI_STRINGS_START+965,
    GUIStr_CreatureMaxHealthDesc = GUI_STRINGS_START+966,
    GUIStr_ToggleMessage = GUI_STRINGS_START+967,
    GUIStr_MnuReturnToFreePlay = GUI_STRINGS_START + 968,
    GUIStr_MnuMapPacks = GUI_STRINGS_START + 969,
    GUIStr_MnuDungeonKeeperLevels = GUI_STRINGS_START+970, // range 970..975
    GUIStr_TrapDoorNames = GUI_STRINGS_START + 981, // range 981..995
    GUIStr_MouseScrollWheelUp = GUI_STRINGS_START + 996,
    GUIStr_MouseScrollWheelDown = GUI_STRINGS_START + 997,
    GUIStr_MouseButton = GUI_STRINGS_START + 998,
    GUIStr_SquareRoomSpace = GUI_STRINGS_START + 999,
    GUIStr_BestRoomSpace = GUI_STRINGS_START + 1000,
    GUIStr_RoomSpaceIncrease = GUI_STRINGS_START + 1001,
    GUIStr_RoomSpaceDecrease = GUI_STRINGS_START + 1002,
    GUIStr_SellTrapOnSubtile = GUI_STRINGS_START + 1003,
    GUIStr_SnapCamera = GUI_STRINGS_START + 1004,
    GUIStr_MysteryBox = GUI_STRINGS_START + 1005,
    GUIStr_NetUnsyncedMap = GUI_STRINGS_START + 1006,
    GUIStr_DisplayResolution = GUI_STRINGS_START + 1007,
    GUIStr_OptionVoice = GUI_STRINGS_START + 1008,
    GUIStr_CtrlTiltUp = GUI_STRINGS_START + 1063,
    GUIStr_CtrlTiltDown = GUI_STRINGS_START + 1064,
    GUIStr_CtrlTiltReset = GUI_STRINGS_START + 1065,
    GUIStr_CtrlAscend = GUI_STRINGS_START + 1078,
    GUIStr_CtrlDescend = GUI_STRINGS_START + 1079,
    GUIStr_Keeper = GUI_STRINGS_START + 1082,
    GUIStr_ScreenRecord,
    GUIStr_ScreenShot,
    GUIStr_FrameSkipIncrease,
    GUIStr_FrameSkipDecrease,
    GUIStr_ZoomMinimapIn,
    GUIStr_ZoomMinimapOut,
    GUIStr_NextInstance,
    GUIStr_PrevInstance = GUI_STRINGS_START + 1090,
    GUIStr_MnuOnlineLobby,
    GUIStr_MnuLanLobby,
    GUIStr_MnuLanLobbies,
    GUIStr_ToggleGui,
    GUIStr_ToggleTooltips = GUI_STRINGS_START + 1095,
    GUIStr_ExitGame = GUI_STRINGS_START + 1099,
    GUIStr_DisablePacketMode,
    GUIStr_SwitchScreenRes,
    GUIStr_ToggleConsole,
    GUIStr_FinishLevel,
    GUIStr_OptionsMenu,
    GUIStr_ToggleHeroHealthFlowers,
    GUIStr_KeyGrave,
    GUIStr_TeleportLastWorkroom,
    GUIStr_TeleportCallToArms,
    GUIStr_TeleportDefault,
    GUIStr_MnuMpMapPacks,
    GUIStr_MnuReturnToLobby,
    GUIStr_NetHostLostWaitingForPlayers,
    GUIStr_NetVerifyFxdataSame,
    GUIStr_NetCustomSpriteMismatch,
    GUIStr_NetAiTookOver,
    GUIStr_NetPlayerLeftGame,
    GUIStr_NetPlayerDisconnected,
    GUIStr_NetUnused,
    GUIStr_NetHostConnectionLost,
    GuiStrEnd
};

enum CampaignStrings {
    CpgStr_SuccessLandIsYours = 0,
    CpgStr_LevelEventMessage = 1, // range 1..200
    CpgStr_Empty = 201,
    CpgStr_LevelName = 202, // range 202..221
    CpgStr_CreatureSpellDesc = 226, // range 226..257
    CpgStr_CreatureKind1 = 258, // range 258..286
    CpgStr_TerrainEmptyLairDesc = 319,
    CpgStr_TerrainVarDesc1 = 324, // range 324..332
    CpgStr_LevelWon = 334,
    CpgStr_LevelLost,
    CpgStr_CreditsHead1 = 362, // range 362..394
    CpgStr_SpecRevealMapDesc = 420,
    CpgStr_SpecResurrectCreatureDesc,
    CpgStr_SpecTransferCreatureDesc,
    CpgStr_SpecStealHeroDesc,
    CpgStr_SpecMultiplyCreaturesDesc,
    CpgStr_SpecIncreaseLevelDesc,
    CpgStr_SpecMakeSafeDesc,
    CpgStr_SpecLocateHiddenWorldDesc,
    CpgStr_SpecResurrectCreature,
    CpgStr_SpecTransferCreature,
    CpgStr_BonusLevel = 430,
    CpgStr_TerrainGemsDesc = 544,
    CpgStr_TerrainHeroEntranceDesc,
    CpgStr_CreatureKind2 = 546, // range 546..547
    CpgStr_RoomKind1 = 552, // range 552..566
    CpgStr_BoulderTrap = 578,
    CpgStr_TrapKindAlarm,
    CpgStr_TrapKindPoisonGas,
    CpgStr_TrapKindLightning,
    CpgStr_TrapKindWordOfPower,
    CpgStr_TrapKindLava,
    CpgStr_TrapBoulderDesc = 584,
    CpgStr_AlarmTrapDesc,
    CpgStr_PoisonGasTrapDesc,
    CpgStr_LightningTrapDesc,
    CpgStr_WordOfPowerTrapDesc,
    CpgStr_LavaTrapDesc,
    CpgStr_DoorKindWooden = 590,
    CpgStr_DoorKindBraced,
    CpgStr_DoorKindIron,
    CpgStr_DoorKindMagic,
    CpgStr_WoodenDoorDesc = 594,
    CpgStr_BracedDoorDesc,
    CpgStr_IronDoorDesc,
    CpgStr_MagicDoorDesc,
    CpgStr_RoomKind2 = 598, // range 598..614
    CpgStr_RoomDesc1 = 615, // range 615..629
    CpgStr_PowerKind1 = 630, // range 630..646
    CpgStr_PowerDesc1 = 647, // range 647..663
};

/******************************************************************************/
/******************************************************************************/
TbBool setup_gui_strings_data(void);
TbBool free_gui_strings_data(void);
TbBool reset_strings(char **strings, int max);
const char * get_string(TextStringId stridx);
TbBool setup_campaign_strings_data(struct GameCampaign *campgn);
TbBool fill_strings_list(char **strings,char *strings_data,char *strings_data_end, int max);
unsigned long count_strings(char *strings, int size);
const char * cmpgn_string(unsigned int index);
/******************************************************************************/
#ifdef __cplusplus
}
#endif
#endif
